"""Shared Issue #104 resident-record catalog, pair analysis, and validator.

This module is the single authority for the relationships in a resident
measurement record.  The builder in :mod:`resident_harness` and the board-free
analyzer both call :func:`validate_resident_record`; neither caller owns a
second copy of these checks.

The outlier builder is the single constructor for the complete pair and
sampler catalog.  The resident runner and board-free analyzer both call
:func:`build_outlier_analysis`; neither caller reconstructs a partial object.
The catalog is intentionally executable.  ``RESIDENT_INVARIANT_CATALOG`` is a
table of ``ResidentInvariant`` entries, and the validator iterates that table
rather than selecting ad-hoc checks in either caller.  The relationships in
the catalog are:

* ``parameters.frame_count`` is the configured attempt count.  Normal runs
  satisfy ``attempted = produced + dropped`` and ``aborted_attempts = 0``;
  error runs satisfy ``attempted = produced + dropped + aborted_attempts`` with
  at most one aborted attempt.  Produced, consumed, dropped, and aborted are
  non-negative and consumed cannot exceed produced.
* ``raw_timestamps.count`` equals the supplied timestamp sequence count when
  available.  The interval count is ``raw_count - 1`` and therefore equals
  ``histogram.N``; histogram bin counts sum to ``N``.  Timestamp count and
  SHA-256 also agree with supplied raw-byte metadata.
* The ring repeats the attempted/produced/consumed/dropped counts, records
  ``producer_full_count = dropped`` and ``overflow_count = producer_full_count``,
  and has occupancy ``produced - consumed`` in ``[0, ring_pages]``.
* ``outlier_analysis`` is generated by :func:`build_outlier_analysis`.  Its
  pair count agrees with starts, pair objects, pair sums, endpoints, event
  arrays, and adjacent start gaps.  Pair object values, sums, order, elapsed
  positions, aggregate sums, gap counts, and duplicate-aware raw
  correspondence are checked whenever the timestamp stream is available.
* A sampled trace's declared filename, columns, byte hash, CSV/sample/valid
  row counts, first/last timestamps, run bounds, in-run AICLK, and PR #109
  ``coverage_complete`` value agree with the actual CSV when bytes are
  supplied.  Sampler-off is absent by design and is diagnostic-only.
* ``telemetry_sampler`` follows the shared ``SAMPLER_CONTRACT``: off has no
  interval, default is exactly 2.0 seconds, and explicit is positive and
  finite.  Top-level and environment copies must agree.
* ``clock.aiclk_mhz`` must equal the AICLK from valid in-run trace samples
  whenever timing evidence is true.  Timing evidence is never accepted for
  sampler-off, Watcher, snapshot-only AICLK, missing/invalid/incomplete
  traces, a clock mismatch, or any corresponding provenance mismatch.  A
  builder call may force the claim false and retain a machine-readable reason;
  an analyzer call reports the mismatch without mutating its input.  The three
  committed ADR-0005 Issue #104 records retain their older schema: absent
  modern pair-detail arrays are treated as legacy compatibility fields, while
  sampled records still fail strict trace-coverage/AICLK validation.

The validator returns a JSON-serializable report with one structured check per
catalog entry.  ``builder=True`` additionally applies the safe timing policy
and raises for hard contradictions when ``raise_on_error`` is true.  Physical
trace availability failures are retained in the report so a builder can write
a diagnostic record, while numeric/schema contradictions remain strict.
"""

from __future__ import annotations

import hashlib
import itertools
import math
from collections import Counter
from collections.abc import Callable, Iterable, Mapping
from dataclasses import dataclass
from fractions import Fraction
from pathlib import Path
from typing import Any

from enodia.tt.bench.sampler_contract import (
    SAMPLER_CONTRACT,
    normalize_sampler_metadata,
)
from enodia.tt.bench.telemetry import POWER_TRACE_COLUMNS, parse_power_trace

CLOCK_MODULUS_TICKS = 1 << 32
DEFAULT_AICLK_MHZ = 1_350
DEFAULT_PHASE_WINDOW_MS = 0.1
PAIR_TARGET_TICKS = 2 * DEFAULT_AICLK_MHZ * 1_000
SHORT_THRESHOLD_TICKS = 1_250_000
LONG_THRESHOLD_TICKS = 1_450_000
PAIR_TOLERANCE_TICKS = 1_000
PAIR_ORDERS = ("short-first", "long-first", "other")

_MISSING = object()


@dataclass(frozen=True)
class ResidentInvariant:
    """One executable record relationship in the shared invariant catalog."""

    name: str
    fields: tuple[str, ...]
    description: str
    check: Callable[[Mapping[str, Any], ValidationContext], list[dict[str, Any]]]


@dataclass(frozen=True)
class ValidationContext:
    """Evidence supplied alongside a record to make derived checks possible."""

    timestamps: list[int] | None
    raw_metadata: Mapping[str, Any] | None
    power_trace_path: Path | None
    power_trace_metadata: Mapping[str, Any] | None
    power_trace_bytes: bytes | None
    strict_trace: bool
    builder: bool


def _mismatch(
    invariant: str,
    fields: Iterable[str],
    message: str,
    *,
    soft: bool = False,
) -> dict[str, Any]:
    return {
        "invariant": invariant,
        "fields": list(fields),
        "message": message,
        "soft": soft,
    }


def _is_int(value: Any, *, nonnegative: bool = False, positive: bool = False) -> bool:
    if isinstance(value, bool) or not isinstance(value, int):
        return False
    if nonnegative and value < 0:
        return False
    return not (positive and value <= 0)


def _is_number(value: Any) -> bool:
    return (
        isinstance(value, (int, float))
        and not isinstance(value, bool)
        and math.isfinite(float(value))
    )


def _value(record: Mapping[str, Any], path: str, default: Any = _MISSING) -> Any:
    current: Any = record
    for component in path.split("."):
        if not isinstance(current, Mapping) or component not in current:
            return default
        current = current[component]
    return current


def _mapping(record: Mapping[str, Any], path: str) -> Mapping[str, Any] | None:
    value = _value(record, path)
    return value if isinstance(value, Mapping) else None


def _pair_order(first: int, second: int) -> str:
    if first < SHORT_THRESHOLD_TICKS and second > LONG_THRESHOLD_TICKS:
        return "short-first"
    if first > LONG_THRESHOLD_TICKS and second < SHORT_THRESHOLD_TICKS:
        return "long-first"
    return "other"


def _is_paired_outlier(first: int, second: int) -> bool:
    return (
        abs(first + second - PAIR_TARGET_TICKS) <= PAIR_TOLERANCE_TICKS
        and _pair_order(first, second) != "other"
    )


def detect_pairs(timestamps: Iterable[int]) -> list[dict[str, Any]]:
    """Detect adjacent short/long pairs using the shared Issue #104 rule."""
    values = list(timestamps)
    if any(not _is_int(value, nonnegative=True) for value in values):
        raise ValueError("timestamps must contain unsigned integer values")
    if any(current <= previous for previous, current in itertools.pairwise(values)):
        raise ValueError("timestamps must be strictly increasing")
    intervals = [current - previous for previous, current in itertools.pairwise(values)]
    pairs: list[dict[str, Any]] = []
    for interval_index, (first, second) in enumerate(itertools.pairwise(intervals)):
        if not _is_paired_outlier(first, second):
            continue
        first_endpoint = interval_index + 1
        first_elapsed = values[first_endpoint] - values[0]
        pair_sum = first + second
        pairs.append(
            {
                "interval_end_frame_indices": [first_endpoint, first_endpoint + 1],
                "short_ticks": min(first, second),
                "long_ticks": max(first, second),
                "first_interval_ticks": first,
                "second_interval_ticks": second,
                "pair_sum_ticks": pair_sum,
                "sum_delta_ticks": pair_sum - PAIR_TARGET_TICKS,
                "order": _pair_order(first, second),
                "first_interval_end_elapsed_ticks": first_elapsed,
                "first_interval_end_elapsed_ticks_mod_period": first_elapsed % CLOCK_MODULUS_TICKS,
            }
        )
    return pairs


# Compatibility spelling used by the board-free analyzer and its existing
# callers.  The implementation remains in this module, not in the analyzer.
_detect_pairs = detect_pairs


def _count_orders(pairs: Iterable[Mapping[str, Any]]) -> dict[str, int]:
    counts = Counter({order: 0 for order in PAIR_ORDERS})
    for pair in pairs:
        order = pair.get("order")
        if order not in counts:
            counts["other"] += 1
        else:
            counts[str(order)] += 1
    return {order: counts[order] for order in PAIR_ORDERS}


def _duplicate_values(values: Iterable[int]) -> list[int]:
    return sorted(value for value, count in Counter(values).items() if count > 1)


def _counter_difference(left: Iterable[int], right: Iterable[int]) -> list[int]:
    return sorted((Counter(left) - Counter(right)).elements())


def _ordered_mismatches(left: list[Any], right: list[Any]) -> list[int]:
    return [
        index
        for index in range(min(len(left), len(right)))
        if left[index] != right[index]
    ]


def _record_pair_starts(record: Mapping[str, Any]) -> list[int]:
    outlier = record.get("outlier_analysis")
    if not isinstance(outlier, Mapping):
        return []
    starts = outlier.get("frame_start_indices", _MISSING)
    pair_count = outlier.get("pair_count")
    pair_sums = outlier.get("pair_sums")
    if starts is _MISSING:
        if type(pair_count) is int and pair_count == 0 and isinstance(pair_sums, list) and not pair_sums:
            return []
        return []
    return list(starts) if isinstance(starts, list) else []


def _record_pairs(record: Mapping[str, Any]) -> list[Mapping[str, Any]]:
    outlier = record.get("outlier_analysis")
    if not isinstance(outlier, Mapping):
        return []
    pairs = outlier.get("pairs", [])
    return list(pairs) if isinstance(pairs, list) else []


def record_correspondence(
    detected_pairs: list[Mapping[str, Any]], record: Mapping[str, Any]
) -> dict[str, Any]:
    """Compare recorded and raw-derived pairs by length, multiset, and order."""
    detected_endpoints = [pair.get("interval_end_frame_indices") for pair in detected_pairs]
    record_starts = _record_pair_starts(record)
    record_pairs = _record_pairs(record)
    record_endpoints = [
        pair.get("interval_end_frame_indices") for pair in record_pairs if isinstance(pair, Mapping)
    ]
    detected_starts = [
        endpoints[0]
        for endpoints in detected_endpoints
        if isinstance(endpoints, list) and endpoints
    ]

    missing = _counter_difference(record_starts, detected_starts)
    unexpected = _counter_difference(detected_starts, record_starts)
    record_duplicate_starts = _duplicate_values(record_starts)
    raw_duplicate_starts = _duplicate_values(detected_starts)
    frame_start_length_match = len(record_starts) == len(detected_starts)
    frame_start_multiset_match = not missing and not unexpected
    frame_start_order_mismatches = _ordered_mismatches(record_starts, detected_starts)
    frame_start_order_match = frame_start_length_match and not frame_start_order_mismatches
    exact_frame_start_match = (
        frame_start_length_match
        and frame_start_multiset_match
        and frame_start_order_match
        and not record_duplicate_starts
    )

    endpoint_mismatches = _ordered_mismatches(detected_endpoints, record_endpoints)
    endpoint_length_match = len(detected_endpoints) == len(record_endpoints)
    missing_endpoint_indices = list(range(len(record_endpoints), len(detected_endpoints)))
    unexpected_endpoint_indices = list(range(len(detected_endpoints), len(record_endpoints)))

    common_pair_count = min(len(detected_pairs), len(record_pairs))
    order_mismatches: list[int] = []
    value_mismatches: list[int] = []
    sum_mismatches: list[int] = []
    for index in range(common_pair_count):
        detected = detected_pairs[index]
        recorded = record_pairs[index]
        if recorded.get("order") is not None and recorded.get("order") != detected.get("order"):
            order_mismatches.append(index)
        if (
            recorded.get("short_ticks") is not None
            and recorded.get("short_ticks") != detected.get("short_ticks")
        ) or (
            recorded.get("long_ticks") is not None
            and recorded.get("long_ticks") != detected.get("long_ticks")
        ):
            value_mismatches.append(index)
        if (
            recorded.get("pair_sum_ticks") is not None
            and recorded.get("pair_sum_ticks") != detected.get("pair_sum_ticks")
        ):
            sum_mismatches.append(index)
    missing_pair_indices = list(range(len(record_pairs), len(detected_pairs)))
    unexpected_pair_indices = list(range(len(detected_pairs), len(record_pairs)))

    return {
        "record_pair_count": len(record_starts),
        "raw_derived_pair_count": len(detected_pairs),
        "record_frame_start_indices": record_starts,
        "raw_derived_frame_start_indices": detected_starts,
        "exact_frame_start_match": exact_frame_start_match,
        "missing_raw_pair_starts": missing,
        "unexpected_raw_pair_starts": unexpected,
        "frame_start_length_match": frame_start_length_match,
        "frame_start_length_mismatch": not frame_start_length_match,
        "frame_start_lengths": {"record": len(record_starts), "raw_derived": len(detected_starts)},
        "record_duplicate_frame_start_indices": record_duplicate_starts,
        "raw_derived_duplicate_frame_start_indices": raw_duplicate_starts,
        "frame_start_multiset_match": frame_start_multiset_match,
        "frame_start_order_match": frame_start_order_match,
        "frame_start_order_mismatches": frame_start_order_mismatches,
        "record_pair_list_count": len(record_pairs),
        "record_pair_list_length_match": len(record_pairs) == len(detected_pairs),
        "record_pair_list_length_mismatch": len(record_pairs) != len(detected_pairs),
        "record_pair_endpoints_present": (
            len(record_endpoints) == len(record_pairs)
            and all(endpoint is not None for endpoint in record_endpoints)
        ),
        "pair_endpoint_list_length_match": endpoint_length_match,
        "pair_endpoint_list_length_mismatch": not endpoint_length_match,
        "pair_endpoint_list_lengths": {
            "record": len(record_endpoints),
            "raw_derived": len(detected_endpoints),
        },
        "pair_endpoint_missing_record_indices": missing_endpoint_indices,
        "pair_endpoint_unexpected_record_indices": unexpected_endpoint_indices,
        "pair_endpoint_mismatches": endpoint_mismatches,
        "pair_endpoint_order_mismatches": endpoint_mismatches,
        "pair_order_mismatches": order_mismatches,
        "pair_order_missing_record_indices": missing_pair_indices,
        "pair_order_unexpected_record_indices": unexpected_pair_indices,
        "pair_value_mismatches": value_mismatches,
        "pair_value_missing_record_indices": missing_pair_indices,
        "pair_value_unexpected_record_indices": unexpected_pair_indices,
        "pair_sum_mismatches": sum_mismatches,
        "pair_sum_missing_record_indices": missing_pair_indices,
        "pair_sum_unexpected_record_indices": unexpected_pair_indices,
    }


_record_correspondence = record_correspondence


def _gcd(values: Iterable[int]) -> int | None:
    result = 0
    found = False
    for value in values:
        result = math.gcd(result, value)
        found = True
    return result if found else None


def _sampler_comparison(
    *,
    sampler_mode: str | None,
    sampler_interval_seconds: float | None,
    timestamps: list[int],
    pair_starts: list[int],
    aiclk_mhz: int,
) -> dict[str, Any]:
    """Compare adjacent paired-event gaps with the configured sampler interval."""
    pair_count = len(pair_starts)
    frame_count = len(timestamps)
    if sampler_mode == "off":
        return {
            "status": "not_applicable",
            "mode": "off",
            "interval_seconds": None,
            "pair_count": pair_count,
            "timestamp_count": frame_count,
            "reason": "sampler_off_by_design; diagnostic-only run",
        }
    if sampler_mode in {"default", "explicit"}:
        if sampler_interval_seconds is None:
            raise ValueError("sampled sampler metadata must include an interval")
        adjacent_gaps: list[dict[str, Any]] = []
        for from_frame, to_frame in itertools.pairwise(pair_starts):
            gap_frames = to_frame - from_frame
            gap_elapsed_seconds = (timestamps[to_frame] - timestamps[from_frame]) / (
                aiclk_mhz * 1_000_000
            )
            sampler_intervals = gap_elapsed_seconds / sampler_interval_seconds
            nearest_integer = round(sampler_intervals)
            adjacent_gaps.append(
                {
                    "from_pair_start_frame": from_frame,
                    "gap_elapsed_seconds": gap_elapsed_seconds,
                    "gap_frames": gap_frames,
                    "nearest_integer_sampler_intervals": nearest_integer,
                    "residual_to_nearest_sampler_multiple_seconds": (
                        gap_elapsed_seconds - nearest_integer * sampler_interval_seconds
                    ),
                    "sampler_intervals": sampler_intervals,
                    "to_pair_start_frame": to_frame,
                }
            )
        return {
            "status": "no_strict_alignment_observed",
            "mode": sampler_mode,
            "interval_seconds": sampler_interval_seconds,
            "sampler_interval_seconds": sampler_interval_seconds,
            "pair_count": pair_count,
            "timestamp_count": frame_count,
            "adjacent_gaps": adjacent_gaps,
            "reason": "pair analysis was computed from the resident timestamp stream",
        }
    return {
        "status": "legacy_unverified",
        "mode": sampler_mode,
        "interval_seconds": sampler_interval_seconds,
        "pair_count": pair_count,
        "timestamp_count": frame_count,
        "reason": "sampler metadata was absent",
    }


def build_outlier_analysis(
    timestamps: Iterable[int],
    *,
    aiclk_mhz: int = DEFAULT_AICLK_MHZ,
    sampler_mode: str | None = None,
    sampler_interval_seconds: float | None = None,
    sampler_metadata: Mapping[str, Any] | None = None,
) -> dict[str, Any]:
    """Build the complete outlier catalog from timestamps and run metadata."""
    if not _is_int(aiclk_mhz, positive=True):
        raise ValueError("aiclk_mhz must be a positive integer")
    if sampler_metadata is not None:
        if sampler_mode is not None or sampler_interval_seconds is not None:
            raise ValueError("sampler metadata cannot be combined with sampler mode arguments")
        sampler = normalize_sampler_metadata(sampler_metadata)
        sampler_mode = sampler["mode"]
        sampler_interval_seconds = sampler["interval_seconds"]
    elif sampler_mode is not None:
        sampler = normalize_sampler_metadata(
            {
                "mode": sampler_mode,
                "interval_seconds": sampler_interval_seconds,
            }
        )
        sampler_mode = sampler["mode"]
        sampler_interval_seconds = sampler["interval_seconds"]
    values = list(timestamps)
    if any(not _is_int(value, nonnegative=True) for value in values):
        raise ValueError("timestamps must contain unsigned integer values")
    if any(current <= previous for previous, current in itertools.pairwise(values)):
        raise ValueError("timestamps must be strictly increasing")
    pairs = detect_pairs(values)
    starts = [pair["interval_end_frame_indices"][0] for pair in pairs]
    endpoints = [endpoint for pair in pairs for endpoint in pair["interval_end_frame_indices"]]
    elapsed_ticks = [values[index] - values[0] for index in endpoints]
    elapsed_mod = [elapsed % CLOCK_MODULUS_TICKS for elapsed in elapsed_ticks]
    elapsed_seconds = [elapsed / (aiclk_mhz * 1_000_000) for elapsed in elapsed_ticks]
    pair_start_elapsed_seconds = [
        (values[index] - values[0]) / (aiclk_mhz * 1_000_000) for index in starts
    ]
    for pair in pairs:
        first_endpoint = pair["interval_end_frame_indices"][0]
        first_elapsed = values[first_endpoint] - values[0]
        pair["first_interval_end_elapsed_seconds"] = first_elapsed / (aiclk_mhz * 1_000_000)
    pair_sums = [pair["pair_sum_ticks"] for pair in pairs]
    gaps = [right - left for left, right in itertools.pairwise(starts)]
    gap_counts = Counter(gaps)
    gap_histogram = [
        {"gap_frames": gap, "count": gap_counts[gap]} for gap in sorted(gap_counts)
    ]
    pair_order_counts = _count_orders(pairs)
    sum_deltas = [pair - PAIR_TARGET_TICKS for pair in pair_sums]
    if pairs:
        most_common_gap, most_common_count = gap_counts.most_common(1)[0] if gap_counts else (None, 0)
        periodicity = (
            f"No single exact period detected; the most common gap is {most_common_gap} frames "
            f"({most_common_count} of {len(gaps)} gaps), and the gap gcd is {_gcd(gaps)}."
            if most_common_gap is not None
            else "One paired outlier was observed; no gap distribution is applicable."
        )
    else:
        periodicity = "No paired short/long outliers were observed; no phase distribution is applicable."
    intervals = [current - previous for previous, current in itertools.pairwise(values)]
    return {
        "method": (
            "short < 1250000 ticks, long > 1450000 ticks, "
            "adjacent pair sum within 1000 ticks of 2700000"
        ),
        "status": "observation_only_no_causal_claim",
        "pair_count": len(pairs),
        "pair_sum_target_ticks": PAIR_TARGET_TICKS,
        "pair_sums": pair_sums,
        "pair_sum_min_ticks": min(pair_sums) if pair_sums else None,
        "pair_sum_max_ticks": max(pair_sums) if pair_sums else None,
        "pair_sum_mean_ticks": sum(pair_sums) / len(pair_sums) if pair_sums else None,
        "sum_delta_min_ticks": min(sum_deltas) if sum_deltas else None,
        "sum_delta_max_ticks": max(sum_deltas) if sum_deltas else None,
        "pair_order_counts": pair_order_counts,
        "frame_start_indices": starts,
        "event_frame_positions": endpoints,
        "event_elapsed_seconds": elapsed_seconds,
        "event_elapsed_ticks": elapsed_ticks,
        "event_elapsed_ticks_mod_period": elapsed_mod,
        "pair_start_elapsed_seconds": pair_start_elapsed_seconds,
        "frame_gaps": gaps,
        "gap_counts": {str(gap): gap_counts[gap] for gap in sorted(gap_counts)},
        "gap_histogram": gap_histogram,
        "gcd_frame_gap": _gcd(gaps),
        "periodicity": periodicity,
        "pairs": pairs,
        "elapsed_time_unit": "seconds",
        "device_tick_unit": "device_clock_ticks",
        "aiclk_mhz_for_elapsed_seconds": aiclk_mhz,
        "run_elapsed_ticks": values[-1] - values[0] if values else 0,
        "run_elapsed_seconds": (
            (values[-1] - values[0]) / (aiclk_mhz * 1_000_000) if values else 0.0
        ),
        "interval_count": len(intervals),
        "sampler_interval_comparison": _sampler_comparison(
            sampler_mode=sampler_mode,
            sampler_interval_seconds=sampler_interval_seconds,
            timestamps=values,
            pair_starts=starts,
            aiclk_mhz=aiclk_mhz,
        ),
    }


# ---------------------------------------------------------------------------
# Invariant checks consumed through RESIDENT_INVARIANT_CATALOG.


def _failure_flag(record: Mapping[str, Any]) -> bool:
    failure = record.get("failure_check")
    if isinstance(failure, Mapping) and isinstance(failure.get("error_flag"), bool):
        return failure["error_flag"]
    if isinstance(failure, Mapping) and _is_int(failure.get("code"), nonnegative=True):
        return failure.get("code") != 0
    return record.get("status") in {"error", "abnormal_exit", "timeout"}


def _check_parameter_counts(record: Mapping[str, Any], ctx: ValidationContext) -> list[dict[str, Any]]:
    del ctx
    invariant = "parameters.counts"
    fields = (
        "parameters.frame_count",
        "parameters.attempted_frame_count",
        "parameters.produced_frame_count",
        "parameters.dropped_frame_count",
        "parameters.aborted_attempts",
    )
    params = _mapping(record, "parameters")
    if params is None:
        return [_mismatch(invariant, fields, "parameters must be an object")]
    mismatches: list[dict[str, Any]] = []
    for name in ("frame_count", "attempted_frame_count", "produced_frame_count", "dropped_frame_count"):
        if not _is_int(params.get(name), nonnegative=True):
            mismatches.append(_mismatch(invariant, (f"parameters.{name}",), f"parameters.{name} must be a non-negative integer"))
    aborted = params.get("aborted_attempts", 0)
    if not _is_int(aborted, nonnegative=True) or aborted not in (0, 1):
        mismatches.append(_mismatch(invariant, ("parameters.aborted_attempts",), "parameters.aborted_attempts must be 0 or 1"))
    frame_count = params.get("frame_count")
    attempted = params.get("attempted_frame_count")
    produced = params.get("produced_frame_count")
    dropped = params.get("dropped_frame_count")
    if all(_is_int(value, nonnegative=True) for value in (frame_count, attempted, produced, dropped)):
        if _failure_flag(record):
            if attempted > frame_count:
                mismatches.append(_mismatch(invariant, ("parameters.frame_count", "parameters.attempted_frame_count"), "error attempted_frame_count cannot exceed configured frame_count"))
        elif frame_count != attempted:
            mismatches.append(_mismatch(invariant, ("parameters.frame_count", "parameters.attempted_frame_count"), "parameters.frame_count must equal attempted_frame_count"))
        if produced > attempted:
            mismatches.append(_mismatch(invariant, ("parameters.produced_frame_count", "parameters.attempted_frame_count"), "produced_frame_count cannot exceed attempted_frame_count"))
        if _failure_flag(record):
            if attempted != produced + dropped + aborted:
                mismatches.append(_mismatch(invariant, fields, "error counter relation requires attempted=produced+dropped+aborted_attempts"))
        elif aborted != 0 or attempted != produced + dropped:
            mismatches.append(_mismatch(invariant, fields, "normal counter relation requires attempted=produced+dropped and aborted_attempts=0"))
    if "frames_produced" in record and record.get("frames_produced") != produced:
        mismatches.append(_mismatch(invariant, ("frames_produced", "parameters.produced_frame_count"), "top-level frames_produced must equal parameters.produced_frame_count"))
    run_budget = params.get("run_budget")
    if isinstance(run_budget, Mapping):
        for budget_name, parameter_name in (
            ("frame_count", "frame_count"),
            ("frame_interval_ticks", "frame_interval_ticks"),
            ("budget_aiclk_mhz", "budget_aiclk_mhz"),
            ("per_frame_work_budget_ticks", "fixed_work_ticks_per_frame"),
            ("cycle_budget_ticks_per_frame", "cycle_budget"),
        ):
            if budget_name in run_budget and parameter_name in params and run_budget.get(budget_name) != params.get(parameter_name):
                mismatches.append(_mismatch(invariant, (f"parameters.run_budget.{budget_name}", f"parameters.{parameter_name}"), f"run_budget.{budget_name} must equal parameters.{parameter_name}"))
    return mismatches


def raw_metadata_matches(record: Mapping[str, Any], metadata: Mapping[str, Any]) -> bool:
    """Return whether declared raw count/hash match supplied raw-byte metadata."""
    raw = record.get("raw_timestamps")
    return (
        isinstance(raw, Mapping)
        and raw.get("count") == metadata.get("count")
        and raw.get("sha256") == metadata.get("sha256")
    )


def _check_raw_timestamps(record: Mapping[str, Any], ctx: ValidationContext) -> list[dict[str, Any]]:
    invariant = "raw_timestamps"
    fields = ("raw_timestamps.count", "raw_timestamps.sha256")
    raw = _mapping(record, "raw_timestamps")
    if raw is None:
        return [_mismatch(invariant, fields, "raw_timestamps must be an object")]
    mismatches: list[dict[str, Any]] = []
    count = raw.get("count")
    digest = raw.get("sha256")
    if not _is_int(count, nonnegative=True):
        mismatches.append(_mismatch(invariant, ("raw_timestamps.count",), "raw_timestamps.count must be a non-negative integer"))
    if not isinstance(digest, str) or len(digest) != 64 or any(char not in "0123456789abcdefABCDEF" for char in digest):
        mismatches.append(_mismatch(invariant, ("raw_timestamps.sha256",), "raw_timestamps.sha256 must be a 64-character hexadecimal digest"))
    if ctx.timestamps is not None:
        if any(not _is_int(value, nonnegative=True) for value in ctx.timestamps):
            mismatches.append(_mismatch(invariant, ("timestamps",), "supplied timestamps must be unsigned integers"))
        if any(current <= previous for previous, current in itertools.pairwise(ctx.timestamps)):
            mismatches.append(_mismatch(invariant, ("timestamps",), "supplied timestamps must be strictly increasing"))
        if _is_int(count, nonnegative=True) and count != len(ctx.timestamps):
            mismatches.append(_mismatch(invariant, ("raw_timestamps.count", "timestamps"), "raw_timestamps.count does not equal timestamp rows"))
    if ctx.raw_metadata is not None:
        actual_count = ctx.raw_metadata.get("count")
        actual_hash = ctx.raw_metadata.get("sha256")
        if _is_int(count, nonnegative=True) and count != actual_count:
            mismatches.append(_mismatch(invariant, ("raw_timestamps.count", "raw_metadata.count"), "raw_timestamps.count does not equal actual raw bytes"))
        if isinstance(digest, str) and digest != actual_hash:
            mismatches.append(_mismatch(invariant, ("raw_timestamps.sha256", "raw_metadata.sha256"), "raw_timestamps.sha256 does not match actual raw bytes"))
    return mismatches


def _intervals(timestamps: list[int]) -> list[int]:
    return [current - previous for previous, current in itertools.pairwise(timestamps)]


def _required_samples(percentile: float) -> int:
    threshold = Fraction(20, 1) / (1 - Fraction(str(percentile)))
    return (threshold.numerator + threshold.denominator - 1) // threshold.denominator


def _linear_percentile(values: list[int], percentile: float) -> float:
    position = (len(values) - 1) * percentile
    lower = math.floor(position)
    upper = math.ceil(position)
    if lower == upper:
        return float(values[lower])
    fraction = position - lower
    return values[lower] + fraction * (values[upper] - values[lower])


def _check_histogram(record: Mapping[str, Any], ctx: ValidationContext) -> list[dict[str, Any]]:
    invariant = "histogram"
    histogram = _mapping(record, "histogram")
    if histogram is None:
        return [_mismatch(invariant, ("histogram",), "histogram must be an object")]
    mismatches: list[dict[str, Any]] = []
    raw = _mapping(record, "raw_timestamps")
    raw_count = raw.get("count") if raw else None
    declared_n = histogram.get("N")
    if not _is_int(declared_n, nonnegative=True):
        mismatches.append(_mismatch(invariant, ("histogram.N",), "histogram.N must be a non-negative integer"))
    expected_n = None
    if _is_int(raw_count, nonnegative=True):
        expected_n = max(0, raw_count - 1)
    if ctx.timestamps is not None:
        expected_n = max(0, len(ctx.timestamps) - 1)
    if expected_n is not None and _is_int(declared_n, nonnegative=True) and declared_n != expected_n:
        mismatches.append(_mismatch(invariant, ("histogram.N", "raw_timestamps.count"), "histogram N must equal interval count (raw timestamp count minus one)"))
    nested = histogram.get("histogram")
    if not isinstance(nested, Mapping):
        mismatches.append(_mismatch(invariant, ("histogram.histogram",), "histogram.histogram must be an object"))
        return mismatches
    bins = nested.get("bins")
    if not isinstance(bins, list):
        mismatches.append(_mismatch(invariant, ("histogram.histogram.bins",), "histogram bins must be a list"))
        return mismatches
    bin_sum = 0
    width = nested.get("bin_width_ticks")
    if not _is_int(width, positive=True):
        mismatches.append(_mismatch(invariant, ("histogram.histogram.bin_width_ticks",), "histogram bin width must be a positive integer"))
    for index, item in enumerate(bins):
        if not isinstance(item, Mapping):
            mismatches.append(_mismatch(invariant, (f"histogram.histogram.bins[{index}]",), "histogram bin must be an object"))
            continue
        count = item.get("count")
        if not _is_int(count, nonnegative=True):
            mismatches.append(_mismatch(invariant, (f"histogram.histogram.bins[{index}].count",), "histogram bin count must be a non-negative integer"))
        else:
            bin_sum += count
        start = item.get("start_ticks")
        end = item.get("end_ticks")
        if not _is_int(start, nonnegative=True) or not _is_int(end, nonnegative=True):
            mismatches.append(_mismatch(invariant, (f"histogram.histogram.bins[{index}]",), "histogram bin endpoints must be non-negative integers"))
        elif _is_int(width, positive=True) and end != start + width:
            mismatches.append(_mismatch(invariant, (f"histogram.histogram.bins[{index}]", "histogram.histogram.bin_width_ticks"), "histogram bin end must equal start plus bin width"))
    if _is_int(declared_n, nonnegative=True) and bin_sum != declared_n:
        mismatches.append(_mismatch(invariant, ("histogram.N", "histogram.histogram.bins"), "histogram bins do not sum to histogram N"))

    if ctx.timestamps is not None and all(_is_int(value, nonnegative=True) for value in ctx.timestamps):
        actual = _intervals(ctx.timestamps)
        ordered = sorted(actual)
        if histogram.get("min_ticks") != (ordered[0] if ordered else None):
            mismatches.append(_mismatch(invariant, ("histogram.min_ticks", "timestamps"), "histogram min_ticks does not match timestamp intervals"))
        if histogram.get("max_ticks") != (ordered[-1] if ordered else None):
            mismatches.append(_mismatch(invariant, ("histogram.max_ticks", "timestamps"), "histogram max_ticks does not match timestamp intervals"))
        if _is_int(width, positive=True):
            expected_bins: dict[int, int] = {}
            for value in ordered:
                start = (value // width) * width
                expected_bins[start] = expected_bins.get(start, 0) + 1
            actual_bins = {
                item.get("start_ticks"): item.get("count")
                for item in bins
                if isinstance(item, Mapping)
            }
            if actual_bins != expected_bins:
                mismatches.append(_mismatch(invariant, ("histogram.histogram.bins", "timestamps"), "histogram bins do not match timestamp intervals"))
        percentiles = histogram.get("percentiles")
        if isinstance(percentiles, Mapping):
            for name, percentile in (("p50", 0.50), ("p99", 0.99), ("p99_9", 0.999), ("p99_99", 0.9999)):
                entry = percentiles.get(name)
                if not isinstance(entry, Mapping):
                    mismatches.append(_mismatch(invariant, (f"histogram.percentiles.{name}",), "histogram percentile entry is missing"))
                    continue
                threshold = _required_samples(percentile)
                expected_status = "ok" if len(ordered) >= threshold else "insufficient"
                if entry.get("status") != expected_status or entry.get("minimum_samples") != threshold:
                    mismatches.append(_mismatch(invariant, (f"histogram.percentiles.{name}", "histogram.N"), "histogram percentile status or minimum_samples is inconsistent with N"))
                if expected_status == "ok" and entry.get("value_ticks") != _linear_percentile(ordered, percentile):
                    mismatches.append(_mismatch(invariant, (f"histogram.percentiles.{name}", "timestamps"), "histogram percentile value does not match timestamp intervals"))
    return mismatches


def validate_pair_analysis(
    outlier_analysis: Mapping[str, Any],
    *,
    timestamps: Iterable[int] | None = None,
    aiclk_mhz: int | None = None,
    sampler_mode: str | None = None,
    sampler_interval_seconds: float | None = None,
) -> list[dict[str, Any]]:
    """Return structured pair-catalog mismatches for builder compatibility callers."""
    invariant = "outlier_analysis"
    if not isinstance(outlier_analysis, Mapping):
        return [_mismatch(invariant, ("outlier_analysis",), "outlier_analysis must be an object")]
    mismatches: list[dict[str, Any]] = []
    timestamp_values = list(timestamps) if timestamps is not None else None
    pair_count = outlier_analysis.get("pair_count")
    if not _is_int(pair_count, nonnegative=True):
        return [_mismatch(invariant, ("outlier_analysis.pair_count",), "outlier_analysis.pair_count must be a non-negative integer")]
    target = outlier_analysis.get("pair_sum_target_ticks", _MISSING)
    if target is not _MISSING and target != PAIR_TARGET_TICKS:
        mismatches.append(_mismatch(invariant, ("outlier_analysis.pair_sum_target_ticks",), "pair_sum_target_ticks does not equal the shared pair target"))
    starts_value = outlier_analysis.get("frame_start_indices", _MISSING)
    if starts_value is _MISSING and pair_count == 0 and outlier_analysis.get("pair_sums") == []:
        starts: list[Any] = []
    elif isinstance(starts_value, list):
        starts = starts_value
    else:
        starts = []
        mismatches.append(_mismatch(invariant, ("outlier_analysis.frame_start_indices",), "outlier_analysis.frame_start_indices must be a list"))
    pairs_value = outlier_analysis.get("pairs", [])
    pairs = pairs_value if isinstance(pairs_value, list) else []
    if not isinstance(pairs_value, list):
        mismatches.append(_mismatch(invariant, ("outlier_analysis.pairs",), "outlier_analysis.pairs must be a list"))
    if len(starts) != pair_count:
        mismatches.append(_mismatch(invariant, ("outlier_analysis.pair_count", "outlier_analysis.frame_start_indices"), "outlier_analysis pair_count must equal frame_start_indices length"))
    if any(not _is_int(value, positive=True) for value in starts):
        mismatches.append(_mismatch(invariant, ("outlier_analysis.frame_start_indices",), "outlier_analysis.frame_start_indices must be positive integers"))
    if len(pairs) != pair_count:
        mismatches.append(_mismatch(invariant, ("outlier_analysis.pair_count", "outlier_analysis.pairs"), "outlier_analysis pair_count must equal pairs length"))
    pair_sums_value = outlier_analysis.get("pair_sums", _MISSING)
    pair_sums: list[Any] | None
    if pair_sums_value is _MISSING:
        pair_sums = None
    elif isinstance(pair_sums_value, list):
        pair_sums = pair_sums_value
        if len(pair_sums) != pair_count:
            mismatches.append(_mismatch(invariant, ("outlier_analysis.pair_count", "outlier_analysis.pair_sums"), "outlier_analysis pair_count must equal pair_sums length"))
    else:
        pair_sums = None
        mismatches.append(_mismatch(invariant, ("outlier_analysis.pair_sums",), "outlier_analysis.pair_sums must be a list"))
    if _duplicate_values(value for value in starts if _is_int(value)):
        mismatches.append(_mismatch(invariant, ("outlier_analysis.frame_start_indices",), "duplicate frame_start_indices are not allowed"))

    for index, pair in enumerate(pairs):
        if not isinstance(pair, Mapping):
            mismatches.append(_mismatch(invariant, (f"outlier_analysis.pairs[{index}]",), "outlier_analysis.pairs must contain objects"))
            continue
        endpoints = pair.get("interval_end_frame_indices")
        if not isinstance(endpoints, list) or len(endpoints) != 2 or any(not _is_int(value, nonnegative=True) for value in endpoints):
            mismatches.append(_mismatch(invariant, (f"outlier_analysis.pairs[{index}].interval_end_frame_indices",), "pair endpoints must contain two non-negative integers"))
            continue
        if index < len(starts) and endpoints != [starts[index], starts[index] + 1]:
            mismatches.append(_mismatch(invariant, (f"outlier_analysis.pairs[{index}]", "outlier_analysis.frame_start_indices"), "outlier_analysis pair endpoints must match frame starts"))
        if pair_sums is not None and index < len(pair_sums) and pair.get("pair_sum_ticks") != pair_sums[index]:
            mismatches.append(_mismatch(invariant, (f"outlier_analysis.pairs[{index}].pair_sum_ticks", "outlier_analysis.pair_sums"), "outlier_analysis pair sums must match pair objects"))

    expected_positions = [endpoint for pair in pairs if isinstance(pair, Mapping) for endpoint in pair.get("interval_end_frame_indices", [])]
    if "event_frame_positions" in outlier_analysis and outlier_analysis.get("event_frame_positions") != expected_positions:
        mismatches.append(_mismatch(invariant, ("outlier_analysis.event_frame_positions", "outlier_analysis.pairs"), "outlier_analysis event frame positions do not match pair endpoints"))
    for field in ("event_elapsed_seconds", "event_elapsed_ticks", "event_elapsed_ticks_mod_period"):
        if field in outlier_analysis:
            values = outlier_analysis.get(field)
            if not isinstance(values, list) or len(values) != pair_count * 2:
                mismatches.append(_mismatch(invariant, (f"outlier_analysis.{field}", "outlier_analysis.pair_count"), f"{field} length does not equal pair endpoint count"))
    starts_int = [value for value in starts if _is_int(value)]
    expected_gaps = [right - left for left, right in itertools.pairwise(starts_int)]
    if "frame_gaps" in outlier_analysis and outlier_analysis.get("frame_gaps") != expected_gaps:
        mismatches.append(_mismatch(invariant, ("outlier_analysis.frame_gaps", "outlier_analysis.frame_start_indices"), "outlier_analysis frame gaps do not match frame starts"))
    if "gap_counts" in outlier_analysis:
        expected_counts = Counter(expected_gaps)
        declared = outlier_analysis.get("gap_counts")
        if not isinstance(declared, Mapping) or {str(key): value for key, value in expected_counts.items()} != dict(declared):
            mismatches.append(_mismatch(invariant, ("outlier_analysis.gap_counts", "outlier_analysis.frame_gaps"), "outlier_analysis gap_counts do not match frame gaps"))
    if "gap_histogram" in outlier_analysis:
        expected_histogram = [{"gap_frames": gap, "count": Counter(expected_gaps)[gap]} for gap in sorted(set(expected_gaps))]
        if outlier_analysis.get("gap_histogram") != expected_histogram:
            mismatches.append(_mismatch(invariant, ("outlier_analysis.gap_histogram", "outlier_analysis.frame_gaps"), "outlier_analysis gap histogram does not match frame gaps"))
    if "gcd_frame_gap" in outlier_analysis and outlier_analysis.get("gcd_frame_gap") != _gcd(expected_gaps):
        mismatches.append(_mismatch(invariant, ("outlier_analysis.gcd_frame_gap", "outlier_analysis.frame_gaps"), "outlier_analysis gcd_frame_gap does not match frame gaps"))

    if timestamp_values is not None:
        values = timestamp_values
        try:
            detected = detect_pairs(values)
        except ValueError as exc:
            mismatches.append(_mismatch(invariant, ("timestamps",), f"pair correspondence cannot be computed: {exc}"))
        else:
            correspondence = record_correspondence(detected, {"outlier_analysis": outlier_analysis})
            if not correspondence["exact_frame_start_match"]:
                mismatches.append(_mismatch(invariant, ("outlier_analysis.frame_start_indices", "timestamps"), "derived pair starts do not match by length, multiset, and order"))
            if not correspondence["record_pair_list_length_match"]:
                mismatches.append(_mismatch(invariant, ("outlier_analysis.pairs", "timestamps"), "derived pair list length does not match record"))
            if correspondence["pair_endpoint_mismatches"]:
                mismatches.append(_mismatch(invariant, ("outlier_analysis.pairs", "timestamps"), "derived pair endpoints do not match record"))
            if correspondence["pair_order_mismatches"]:
                mismatches.append(_mismatch(invariant, ("outlier_analysis.pairs", "timestamps"), "derived pair orders do not match record"))
            if correspondence["pair_value_mismatches"]:
                mismatches.append(_mismatch(invariant, ("outlier_analysis.pairs", "timestamps"), "derived pair values do not match record"))
            if correspondence["pair_sum_mismatches"]:
                mismatches.append(_mismatch(invariant, ("outlier_analysis.pairs", "timestamps"), "derived pair sums do not match record"))
            actual_aiclk = aiclk_mhz if _is_int(aiclk_mhz, positive=True) else DEFAULT_AICLK_MHZ
            expected_pairs = build_outlier_analysis(values, aiclk_mhz=actual_aiclk).get("pairs", [])
            if "interval_count" in outlier_analysis and outlier_analysis.get("interval_count") != len(values) - 1:
                mismatches.append(_mismatch(invariant, ("outlier_analysis.interval_count", "timestamps"), "outlier_analysis interval_count does not match timestamps"))
            for index, pair in enumerate(pairs):
                if index >= len(expected_pairs) or not isinstance(pair, Mapping):
                    continue
                expected = expected_pairs[index]
                for field in (
                    "first_interval_ticks",
                    "second_interval_ticks",
                    "short_ticks",
                    "long_ticks",
                    "pair_sum_ticks",
                    "sum_delta_ticks",
                    "order",
                    "first_interval_end_elapsed_ticks",
                    "first_interval_end_elapsed_ticks_mod_period",
                    "first_interval_end_elapsed_seconds",
                ):
                    if field in pair and pair.get(field) != expected.get(field):
                        mismatches.append(_mismatch(invariant, (f"outlier_analysis.pairs[{index}].{field}", "timestamps"), f"pair {index} {field} does not match timestamps"))
            expected_pair_sums = [pair["pair_sum_ticks"] for pair in expected_pairs]
            if pair_sums is not None and pair_sums != expected_pair_sums:
                mismatches.append(_mismatch(invariant, ("outlier_analysis.pair_sums", "timestamps"), "outlier_analysis pair_sums do not match timestamps"))
            expected_endpoints = [endpoint for pair in expected_pairs for endpoint in pair["interval_end_frame_indices"]]
            expected_elapsed_ticks = [values[index] - values[0] for index in expected_endpoints]
            expected_elapsed_mod = [elapsed % CLOCK_MODULUS_TICKS for elapsed in expected_elapsed_ticks]
            actual_seconds_aiclk = aiclk_mhz if _is_int(aiclk_mhz, positive=True) else DEFAULT_AICLK_MHZ
            expected_elapsed_seconds = [elapsed / (actual_seconds_aiclk * 1_000_000) for elapsed in expected_elapsed_ticks]
            for field, expected in (
                ("event_frame_positions", expected_endpoints),
                ("event_elapsed_ticks", expected_elapsed_ticks),
                ("event_elapsed_ticks_mod_period", expected_elapsed_mod),
                ("event_elapsed_seconds", expected_elapsed_seconds),
                ("pair_start_elapsed_seconds", [
                    (values[index] - values[0]) / (actual_seconds_aiclk * 1_000_000)
                    for index in [pair["interval_end_frame_indices"][0] for pair in expected_pairs]
                ]),
            ):
                if field in outlier_analysis and outlier_analysis.get(field) != expected:
                    mismatches.append(_mismatch(invariant, (f"outlier_analysis.{field}", "timestamps"), f"outlier_analysis {field} does not match timestamps"))
            expected_sums = [pair["pair_sum_ticks"] for pair in expected_pairs]
            for field, expected in (
                ("pair_sum_min_ticks", min(expected_sums) if expected_sums else None),
                ("pair_sum_max_ticks", max(expected_sums) if expected_sums else None),
                ("pair_sum_mean_ticks", sum(expected_sums) / len(expected_sums) if expected_sums else None),
                ("sum_delta_min_ticks", min((value - PAIR_TARGET_TICKS) for value in expected_sums) if expected_sums else None),
                ("sum_delta_max_ticks", max((value - PAIR_TARGET_TICKS) for value in expected_sums) if expected_sums else None),
                ("aiclk_mhz_for_elapsed_seconds", actual_seconds_aiclk),
                ("run_elapsed_ticks", values[-1] - values[0] if values else 0),
                ("run_elapsed_seconds", (values[-1] - values[0]) / (actual_seconds_aiclk * 1_000_000) if values else 0.0),
            ):
                if field in outlier_analysis and outlier_analysis.get(field) != expected:
                    mismatches.append(_mismatch(invariant, (f"outlier_analysis.{field}", "timestamps"), f"outlier_analysis {field} does not match timestamps"))
    # Pair sums and order metadata are derivable even without raw timestamps.
    object_sums = [pair.get("pair_sum_ticks") for pair in pairs if isinstance(pair, Mapping) and _is_int(pair.get("pair_sum_ticks"))]
    if "pair_sum_min_ticks" in outlier_analysis and outlier_analysis.get("pair_sum_min_ticks") != (min(object_sums) if object_sums else None):
        mismatches.append(_mismatch(invariant, ("outlier_analysis.pair_sum_min_ticks", "outlier_analysis.pairs"), "pair_sum_min_ticks does not match pair objects"))
    if "pair_sum_max_ticks" in outlier_analysis and outlier_analysis.get("pair_sum_max_ticks") != (max(object_sums) if object_sums else None):
        mismatches.append(_mismatch(invariant, ("outlier_analysis.pair_sum_max_ticks", "outlier_analysis.pairs"), "pair_sum_max_ticks does not match pair objects"))
    if "pair_sum_mean_ticks" in outlier_analysis and outlier_analysis.get("pair_sum_mean_ticks") != (sum(object_sums) / len(object_sums) if object_sums else None):
        mismatches.append(_mismatch(invariant, ("outlier_analysis.pair_sum_mean_ticks", "outlier_analysis.pairs"), "pair_sum_mean_ticks does not match pair objects"))
    object_deltas = [value - PAIR_TARGET_TICKS for value in object_sums]
    if "sum_delta_min_ticks" in outlier_analysis and outlier_analysis.get("sum_delta_min_ticks") != (min(object_deltas) if object_deltas else None):
        mismatches.append(_mismatch(invariant, ("outlier_analysis.sum_delta_min_ticks", "outlier_analysis.pairs"), "sum_delta_min_ticks does not match pair objects"))
    if "sum_delta_max_ticks" in outlier_analysis and outlier_analysis.get("sum_delta_max_ticks") != (max(object_deltas) if object_deltas else None):
        mismatches.append(_mismatch(invariant, ("outlier_analysis.sum_delta_max_ticks", "outlier_analysis.pairs"), "sum_delta_max_ticks does not match pair objects"))
    if "pair_order_counts" in outlier_analysis and outlier_analysis.get("pair_order_counts") != _count_orders(pair for pair in pairs if isinstance(pair, Mapping)):
        mismatches.append(_mismatch(invariant, ("outlier_analysis.pair_order_counts", "outlier_analysis.pairs"), "pair_order_counts does not match pair objects"))

    if timestamp_values is not None and sampler_mode in {"off", "default", "explicit"}:
        actual_timestamps = timestamp_values
        expected = build_outlier_analysis(
            actual_timestamps,
            aiclk_mhz=(aiclk_mhz if _is_int(aiclk_mhz, positive=True) else DEFAULT_AICLK_MHZ),
            sampler_mode=sampler_mode,
            sampler_interval_seconds=sampler_interval_seconds,
        )["sampler_interval_comparison"]
        actual = outlier_analysis.get("sampler_interval_comparison")
        if isinstance(actual, Mapping):
            for field, expected_value in expected.items():
                if field in actual and actual.get(field) != expected_value:
                    mismatches.append(
                        _mismatch(
                            invariant,
                            (f"outlier_analysis.sampler_interval_comparison.{field}", "timestamps"),
                            f"sampler interval comparison {field} does not match timestamps",
                        )
                    )
        elif sampler_mode != "off":
            mismatches.append(
                _mismatch(
                    invariant,
                    ("outlier_analysis.sampler_interval_comparison",),
                    "sampled outlier analysis must include sampler interval comparison",
                )
            )

    return mismatches


def _check_pairs(record: Mapping[str, Any], ctx: ValidationContext) -> list[dict[str, Any]]:
    outlier = record.get("outlier_analysis")
    if not isinstance(outlier, Mapping):
        return [_mismatch("outlier_analysis", ("outlier_analysis",), "record is missing outlier_analysis")]
    mismatches: list[dict[str, Any]] = []
    schema = record.get("schema")
    legacy = isinstance(schema, str) and schema.startswith("adr-0005-issue-104-")
    if not legacy:
        required = (
            "pair_sum_target_ticks",
            "pair_sums",
            "frame_start_indices",
            "pairs",
            "event_frame_positions",
            "event_elapsed_seconds",
            "event_elapsed_ticks",
            "event_elapsed_ticks_mod_period",
            "frame_gaps",
            "gap_counts",
            "gap_histogram",
            "gcd_frame_gap",
            "interval_count",
            "pair_order_counts",
            "sampler_interval_comparison",
        )
        for field in required:
            if field not in outlier:
                mismatches.append(_mismatch("outlier_analysis", (f"outlier_analysis.{field}",), f"outlier_analysis.{field} is required by the resident schema"))
    if not legacy and isinstance(outlier.get("pairs"), list):
        pair_fields = (
            "interval_end_frame_indices",
            "first_interval_ticks",
            "second_interval_ticks",
            "short_ticks",
            "long_ticks",
            "pair_sum_ticks",
            "sum_delta_ticks",
            "order",
            "first_interval_end_elapsed_ticks",
            "first_interval_end_elapsed_ticks_mod_period",
            "first_interval_end_elapsed_seconds",
        )
        for index, pair in enumerate(outlier["pairs"]):
            if isinstance(pair, Mapping):
                for field in pair_fields:
                    if field not in pair:
                        mismatches.append(_mismatch("outlier_analysis", (f"outlier_analysis.pairs[{index}].{field}",), f"pair {index} {field} is required by the resident schema"))
    clock = _mapping(record, "clock")
    aiclk = clock.get("aiclk_mhz") if clock else None
    sampler = _sampler(record)
    sampler_mode = (
        sampler.get("mode")
        if isinstance(sampler, Mapping) and sampler.get("mode") in {"off", "default", "explicit"}
        else None
    )
    sampler_interval_seconds = (
        sampler.get("interval_seconds") if isinstance(sampler, Mapping) else None
    )
    mismatches.extend(
        validate_pair_analysis(
            outlier,
            timestamps=ctx.timestamps,
            aiclk_mhz=aiclk,
            sampler_mode=sampler_mode,
            sampler_interval_seconds=sampler_interval_seconds,
        )
    )

    comparison = outlier.get("sampler_interval_comparison")
    if (
        isinstance(comparison, Mapping)
        and isinstance(sampler, Mapping)
        and sampler.get("mode") != "__mismatch__"
        and ("mode" in comparison or "interval_seconds" in comparison)
    ):
        if "mode" in comparison and comparison.get("mode") != sampler.get("mode"):
            mismatches.append(_mismatch("outlier_analysis", ("outlier_analysis.sampler_interval_comparison.mode", "telemetry_sampler.mode"), "sampler comparison mode does not match record sampler mode"))
        for comparison_field in ("interval_seconds", "sampler_interval_seconds"):
            if (
                comparison_field in comparison
                and comparison.get(comparison_field) != sampler.get("interval_seconds")
            ):
                mismatches.append(
                    _mismatch(
                        "outlier_analysis",
                        (
                            f"outlier_analysis.sampler_interval_comparison.{comparison_field}",
                            "telemetry_sampler.interval_seconds",
                        ),
                        "sampler comparison interval does not match record sampler interval",
                    )
                )
    return mismatches


def _check_ring(record: Mapping[str, Any], ctx: ValidationContext) -> list[dict[str, Any]]:
    invariant = "ring.counts"
    ring = _mapping(record, "ring")
    params = _mapping(record, "parameters")
    if ring is None:
        return [_mismatch(invariant, ("ring",), "ring must be an object")]
    if params is None:
        return [_mismatch(invariant, ("ring", "parameters"), "ring cannot be checked without parameters")]
    mismatches: list[dict[str, Any]] = []
    pairs = (
        ("attempted_frame_count", "attempted"),
        ("produced_frame_count", "produced"),
        ("dropped_frame_count", "dropped"),
        ("aborted_attempts", "aborted"),
    )
    for ring_name, parameter_name in pairs:
        ring_value = ring.get(ring_name, 0) if ring_name == "aborted_attempts" else ring.get(ring_name)
        param_value = params.get({"attempted": "attempted_frame_count", "produced": "produced_frame_count", "dropped": "dropped_frame_count", "aborted": "aborted_attempts"}[parameter_name], 0)
        if not _is_int(ring_value, nonnegative=True):
            mismatches.append(_mismatch(invariant, (f"ring.{ring_name}",), f"ring.{ring_name} must be a non-negative integer"))
        if _is_int(ring_value, nonnegative=True) and ring_value != param_value:
            mismatches.append(_mismatch(invariant, (f"ring.{ring_name}", f"parameters.{parameter_name}_frame_count"), f"ring.{ring_name} must equal parameters.{parameter_name}_frame_count"))
    for name in ("producer_full_count", "consumer_empty_count", "overflow_count"):
        if not _is_int(ring.get(name), nonnegative=True):
            mismatches.append(_mismatch(invariant, (f"ring.{name}",), f"ring.{name} must be a non-negative integer"))
    if _is_int(ring.get("producer_full_count"), nonnegative=True) and ring.get("producer_full_count") != params.get("dropped_frame_count"):
        mismatches.append(_mismatch(invariant, ("ring.producer_full_count", "parameters.dropped_frame_count"), "producer_full_count must equal dropped_frame_count"))
    if _is_int(ring.get("overflow_count"), nonnegative=True) and ring.get("overflow_count") != ring.get("producer_full_count"):
        mismatches.append(_mismatch(invariant, ("ring.overflow_count", "ring.producer_full_count"), "overflow_count must equal producer_full_count"))
    consumed = ring.get("consumed_frame_count")
    produced = ring.get("produced_frame_count")
    if not _is_int(consumed, nonnegative=True):
        mismatches.append(_mismatch(invariant, ("ring.consumed_frame_count",), "ring.consumed_frame_count must be a non-negative integer"))
    expected_consumed = len(ctx.timestamps) if ctx.timestamps is not None else _value(record, "raw_timestamps.count")
    if _is_int(consumed, nonnegative=True) and _is_int(expected_consumed, nonnegative=True) and consumed != expected_consumed:
        mismatches.append(_mismatch(invariant, ("ring.consumed_frame_count", "raw_timestamps.count"), "ring consumed_frame_count must equal raw timestamp count"))
    if _is_int(consumed, nonnegative=True) and _is_int(produced, nonnegative=True):
        if consumed > produced:
            mismatches.append(_mismatch(invariant, ("ring.consumed_frame_count", "ring.produced_frame_count"), "consumed_frame_count cannot exceed produced_frame_count"))
        ring_pages = params.get("ring_pages")
        if _is_int(ring_pages, nonnegative=True) and produced - consumed > ring_pages:
            mismatches.append(_mismatch(invariant, ("ring.produced_frame_count", "ring.consumed_frame_count", "parameters.ring_pages"), "ring occupancy produced-consumed exceeds ring_pages"))
    if "frames_consumed" in record and record.get("frames_consumed") != consumed:
        mismatches.append(_mismatch(invariant, ("frames_consumed", "ring.consumed_frame_count"), "top-level frames_consumed must equal ring consumed_frame_count"))
    return mismatches


def _sampler(record: Mapping[str, Any]) -> Mapping[str, Any] | None:
    top_present = "telemetry_sampler" in record
    top = record.get("telemetry_sampler")
    environment = record.get("environment")
    nested_present = isinstance(environment, Mapping) and "telemetry_sampler" in environment
    nested = environment.get("telemetry_sampler") if isinstance(environment, Mapping) else None
    if top_present and not isinstance(top, Mapping):
        return {"mode": "__mismatch__", "top": top, "nested": nested}
    if nested_present and not isinstance(nested, Mapping):
        return {"mode": "__mismatch__", "top": top, "nested": nested}
    if isinstance(top, Mapping) and isinstance(nested, Mapping):
        compared = ("mode", "interval_seconds", "power_trace", "timing_evidence")
        if any(top.get(key) != nested.get(key) for key in compared):
            return {"mode": "__mismatch__", "top": top, "nested": nested}
    if isinstance(top, Mapping):
        return top
    if isinstance(nested, Mapping):
        return nested
    return None


def _check_sampler_contract(record: Mapping[str, Any], ctx: ValidationContext) -> list[dict[str, Any]]:
    del ctx
    invariant = "sampler.trace_contract"
    sampler = _sampler(record)
    if sampler is None:
        return []
    if sampler.get("mode") == "__mismatch__":
        top = sampler.get("top")
        mode = top.get("mode") if isinstance(top, Mapping) else None
        if mode in {"default", "explicit"}:
            return [_mismatch(invariant, ("telemetry_sampler", "environment.telemetry_sampler"), "sampled sampler mode requires matching trace metadata")]
        return [_mismatch(invariant, ("telemetry_sampler", "environment.telemetry_sampler"), "top-level and environment sampler metadata disagree")]

    try:
        canonical = normalize_sampler_metadata(sampler, complete_default=False)
    except (TypeError, ValueError) as exc:
        field = (
            "telemetry_sampler.interval_seconds"
            if "interval" in str(exc)
            else "telemetry_sampler.mode"
        )
        return [_mismatch(invariant, (field,), f"sampler contract violation: {exc}")]

    mode = canonical["mode"]
    contract = SAMPLER_CONTRACT[mode]
    trace_name = record.get("power_trace")
    mismatches: list[dict[str, Any]] = []
    if sampler.get("power_trace") != contract["power_trace"]:
        mismatches.append(_mismatch(invariant, ("telemetry_sampler.power_trace",), "sampler power_trace metadata does not match sampler mode"))
    if sampler.get("timing_evidence") != contract["timing_evidence"]:
        mismatches.append(_mismatch(invariant, ("telemetry_sampler.timing_evidence",), "sampler timing_evidence metadata does not match sampler mode"))
    if mode == "off":
        if trace_name is not None:
            mismatches.append(_mismatch(invariant, ("power_trace", "telemetry_sampler.mode"), "sampler-off records must omit the power trace"))
        if record.get("power_trace_absent_reason") != "sampler_off_by_design":
            mismatches.append(_mismatch(invariant, ("power_trace_absent_reason",), "sampler-off records require sampler_off_by_design"))
    else:
        if not isinstance(trace_name, str) or not trace_name.strip() or Path(trace_name).name != trace_name:
            mismatches.append(_mismatch(invariant, ("power_trace", "telemetry_sampler.mode"), "sampled sampler mode requires a power trace basename"))
    return mismatches


def _declared_power_metadata(record: Mapping[str, Any]) -> dict[str, Any]:
    provenance = record.get("power_clock_provenance")
    nested = dict(provenance) if isinstance(provenance, Mapping) else {}
    aliases = {
        "file": ("file", "trace"),
        "sample_count": ("sample_count",),
        "csv_row_count": ("csv_row_count",),
        "valid_row_count": ("valid_row_count",),
        "in_run_valid_row_count": ("in_run_valid_row_count",),
        "sha256": ("sha256",),
        "columns": ("columns",),
        "first_timestamp": ("first_timestamp",),
        "last_timestamp": ("last_timestamp",),
        "run_start": ("run_start",),
        "run_end": ("run_end",),
        "coverage_complete": ("coverage_complete",),
        "aiclk_source": ("aiclk_source",),
        "aiclk_mhz": ("aiclk_mhz",),
        "timing_evidence_reason": ("timing_evidence_reason",),
    }
    top = {
        "file": record.get("power_trace"),
        "sample_count": record.get("power_trace_sample_count", _MISSING),
        "csv_row_count": record.get("power_trace_csv_row_count", _MISSING),
        "valid_row_count": record.get("power_trace_valid_row_count", _MISSING),
        "in_run_valid_row_count": record.get("power_trace_in_run_valid_row_count", _MISSING),
        "sha256": record.get("power_trace_sha256", _MISSING),
        "columns": _MISSING,
        "first_timestamp": _MISSING,
        "last_timestamp": _MISSING,
        "run_start": record.get("run_start", _MISSING),
        "run_end": record.get("run_end", _MISSING),
        "coverage_complete": _MISSING,
        "aiclk_source": _MISSING,
        "aiclk_mhz": _MISSING,
        "timing_evidence_reason": _MISSING,
    }
    coverage = record.get("power_trace_coverage")
    if isinstance(coverage, Mapping):
        top["coverage_complete"] = coverage.get("coverage_complete", coverage.get("complete", _MISSING))
        top["first_timestamp"] = coverage.get("first_timestamp", _MISSING)
        top["last_timestamp"] = coverage.get("last_timestamp", _MISSING)
        top["run_start"] = coverage.get("run_start", top["run_start"])
        top["run_end"] = coverage.get("run_end", top["run_end"])
    result: dict[str, Any] = {}
    for name, keys in aliases.items():
        value = _MISSING
        for key in keys:
            if key in nested:
                value = nested[key]
                break
        if value is _MISSING:
            value = top[name]
        result[name] = value
    result["nested"] = nested
    result["top"] = top
    return result


def _trace_report(record: Mapping[str, Any], ctx: ValidationContext) -> dict[str, Any] | None:
    sampler = _sampler(record)
    mode = sampler.get("mode") if isinstance(sampler, Mapping) else None
    trace_name = record.get("power_trace")
    if mode not in {"default", "explicit"} or not trace_name:
        return None
    declared = _declared_power_metadata(record)
    run_start = declared.get("run_start")
    run_end = declared.get("run_end")
    if ctx.power_trace_path is not None:
        report = parse_power_trace(ctx.power_trace_path, run_start=None if run_start is _MISSING else run_start, run_end=None if run_end is _MISSING else run_end)
        report["actual_bytes_available"] = True
        return report
    if ctx.power_trace_metadata is not None:
        report = dict(ctx.power_trace_metadata)
        report.setdefault("file", trace_name)
        report["actual_bytes_available"] = False
        return report
    if ctx.power_trace_bytes is not None:
        return {
            "file": trace_name,
            "sha256": hashlib.sha256(ctx.power_trace_bytes).hexdigest(),
            "actual_bytes_available": True,
            "readable": False,
            "coverage_complete": False,
            "aiclk_source": "no_valid_in_run_samples",
        }
    return {"file": trace_name, "actual_bytes_available": False, "reason": "power_trace_bytes_unavailable"}


def _check_power_trace_facts(record: Mapping[str, Any], ctx: ValidationContext) -> list[dict[str, Any]]:
    invariant = "power_trace.facts"
    sampler = _sampler(record)
    mode = sampler.get("mode") if isinstance(sampler, Mapping) else None
    if mode not in {"default", "explicit"} or not record.get("power_trace"):
        return []
    declared = _declared_power_metadata(record)
    report = _trace_report(record, ctx)
    if report is None:
        return []
    mismatches: list[dict[str, Any]] = []
    trace_name = record.get("power_trace")
    if declared.get("file", _MISSING) not in {_MISSING, None, trace_name}:
        mismatches.append(_mismatch(invariant, ("power_trace", "power_clock_provenance.file"), "power trace filename does not match record"))
    actual_file = report.get("file")
    if actual_file is not None and actual_file != trace_name:
        mismatches.append(_mismatch(invariant, ("power_trace",), "power trace path basename does not match record"))
    actual_hash = report.get("sha256")
    declared_hash = declared.get("sha256", _MISSING)
    if actual_hash is not None and declared_hash is not _MISSING and declared_hash is not None and declared_hash != actual_hash:
        mismatches.append(_mismatch(invariant, ("power_trace_sha256", "power_clock_provenance.sha256"), "power trace SHA-256 does not match actual bytes"))
    if ctx.power_trace_bytes is not None:
        supplied_hash = hashlib.sha256(ctx.power_trace_bytes).hexdigest()
        if declared_hash is _MISSING or declared_hash != supplied_hash:
            mismatches.append(_mismatch(invariant, ("power_trace_sha256",), "power trace SHA-256 does not match supplied bytes"))
    # A builder's basename-only compatibility branch is intentionally
    # diagnostic.  A strict analyzer read still reports unavailable facts.
    legacy_unverified = declared.get("aiclk_source") == "legacy_unverified"
    actual_available = report.get("actual_bytes_available") is True
    required_fields = (
        "columns",
        "sample_count",
        "csv_row_count",
        "valid_row_count",
        "in_run_valid_row_count",
        "first_timestamp",
        "last_timestamp",
        "run_start",
        "run_end",
        "coverage_complete",
        "aiclk_source",
    )
    if not actual_available and legacy_unverified:
        return mismatches
    if not actual_available:
        mismatches.append(_mismatch(invariant, ("power_trace",), "power trace actual bytes are unavailable for SHA-256 and row validation"))
        return mismatches
    if report.get("columns") != list(POWER_TRACE_COLUMNS):
        mismatches.append(_mismatch(invariant, ("power_trace.columns",), "power trace columns are not the declared telemetry columns"))
    for field in ("readable", "nonempty", "timestamps_parse", "timestamps_ordered"):
        if report.get(field) is not True:
            mismatches.append(_mismatch(invariant, (f"power_trace.{field}",), f"power trace {field} is not true"))
    if report.get("sample_count") != report.get("csv_row_count"):
        mismatches.append(_mismatch(invariant, ("power_trace.sample_count", "power_trace.csv_row_count"), "power trace sample_count does not equal CSV row count"))
    if report.get("valid_row_count") != report.get("csv_row_count"):
        mismatches.append(_mismatch(invariant, ("power_trace.valid_row_count", "power_trace.csv_row_count"), "power trace valid-row count does not equal CSV row count"))
    for field in required_fields:
        declared_value = declared.get(field, _MISSING)
        if declared_value is _MISSING or declared_value is None:
            mismatches.append(_mismatch(invariant, (f"power_clock_provenance.{field}",), f"power trace {field} is not declared"))
        elif declared_value != report.get(field):
            mismatches.append(_mismatch(invariant, (f"power_clock_provenance.{field}",), f"power trace {field} does not match actual trace"))
    if report.get("coverage_complete") is not True:
        mismatches.append(_mismatch(invariant, ("power_trace.coverage_complete",), "power trace coverage_complete is not true"))
    # Both nested and top-level fields are part of the record schema when
    # present; disagreement is never silently resolved by precedence.
    duplicate_fields = {
        "file": "power_trace",
        "sample_count": "power_trace_sample_count",
        "csv_row_count": "power_trace_csv_row_count",
        "valid_row_count": "power_trace_valid_row_count",
        "in_run_valid_row_count": "power_trace_in_run_valid_row_count",
        "sha256": "power_trace_sha256",
        "first_timestamp": "power_trace_coverage.first_timestamp",
        "last_timestamp": "power_trace_coverage.last_timestamp",
        "run_start": "run_start",
        "run_end": "run_end",
        "coverage_complete": "power_trace_coverage.coverage_complete",
        "aiclk_source": "clock.aiclk_source",
        "aiclk_mhz": "clock.aiclk_mhz",
    }
    nested = declared.get("nested", {})
    top = declared.get("top", {})
    for nested_name, top_name in duplicate_fields.items():
        nested_value = nested.get(nested_name, _MISSING)
        top_value = top.get(nested_name, _MISSING)
        if nested_name == "aiclk_source" and top_value is _MISSING:
            clock = _mapping(record, "clock")
            top_value = clock.get("aiclk_source", _MISSING) if clock else _MISSING
        if nested_name == "aiclk_mhz" and top_value is _MISSING:
            clock = _mapping(record, "clock")
            top_value = clock.get("aiclk_mhz", _MISSING) if clock else _MISSING
        if nested_value is not _MISSING and top_value is not _MISSING and nested_value != top_value:
            label = "SHA-256" if nested_name == "sha256" else nested_name
            mismatches.append(_mismatch(invariant, (f"power_clock_provenance.{nested_name}", top_name), f"power provenance {label} does not match {top_name}"))
    return mismatches


def _timing_block_reason(record: Mapping[str, Any], ctx: ValidationContext, report: Mapping[str, Any] | None) -> str | None:
    sampler = _sampler(record)
    mode = sampler.get("mode") if isinstance(sampler, Mapping) else None
    if mode == "off":
        return "sampler_off_by_design"
    if record.get("watcher") is True:
        return "watcher_diagnostic_only"
    if not record.get("power_trace"):
        return "power_trace_missing"
    declared = _declared_power_metadata(record)
    legacy_unverified = declared.get("aiclk_source") == "legacy_unverified" and ctx.power_trace_path is None and ctx.power_trace_metadata is not None
    if report is None:
        return "power_trace_bytes_unavailable"
    if legacy_unverified:
        return None
    if report.get("readable") is not True or report.get("nonempty") is not True:
        return "power_trace_unreadable"
    if report.get("coverage_complete") is not True:
        return "power_trace_coverage_incomplete"
    if report.get("in_run_valid_row_count", 0) < 1 or report.get("aiclk_source") != "run_trace_samples":
        return "power_trace_no_valid_in_run_rows"
    clock = _mapping(record, "clock")
    clock_aiclk = clock.get("aiclk_mhz") if clock else None
    trace_aiclk = report.get("aiclk_mhz")
    if clock_aiclk != trace_aiclk:
        return "clock_aiclk_mismatch"
    if declared.get("aiclk_source") != "run_trace_samples":
        return "power_trace_aiclk_not_in_run"
    if _failure_flag(record):
        return "run_error_not_timing_evidence"
    params = _mapping(record, "parameters")
    ring = _mapping(record, "ring")
    if params and ring:
        if params.get("dropped_frame_count") != 0 or ring.get("consumed_frame_count") != params.get("produced_frame_count"):
            return "run_incomplete_or_dropped_frames"
        if params.get("attempted_frame_count") != params.get("frame_count"):
            return "run_incomplete_or_dropped_frames"
    source_evidence = _mapping(record, "clock_source_evidence")
    if source_evidence and source_evidence.get("audit_status") not in {None, "audited"}:
        return "clock_source_unaudited"
    return None


def _check_clock_and_timing(record: Mapping[str, Any], ctx: ValidationContext) -> list[dict[str, Any]]:
    invariant = "clock.timing_evidence"
    timing = record.get("timing_evidence", _MISSING)
    sampler = _sampler(record)
    mode = sampler.get("mode") if isinstance(sampler, Mapping) else None
    report = _trace_report(record, ctx)
    declared = _declared_power_metadata(record)
    mismatches: list[dict[str, Any]] = []
    clock = _mapping(record, "clock")
    clock_aiclk = clock.get("aiclk_mhz") if clock else _MISSING
    if clock is not None and not _is_int(clock_aiclk, positive=True):
        mismatches.append(_mismatch(invariant, ("clock.aiclk_mhz",), "clock.aiclk_mhz must be a positive integer"))
    declared_aiclk = declared.get("aiclk_mhz", _MISSING)
    if declared_aiclk is not _MISSING and declared_aiclk is not None and _is_int(clock_aiclk, positive=True) and declared_aiclk != clock_aiclk:
        mismatches.append(_mismatch(invariant, ("clock.aiclk_mhz", "power_clock_provenance.aiclk_mhz"), "power provenance AICLK does not match clock.aiclk_mhz"))
    if report is not None and report.get("aiclk_mhz") is not None and _is_int(clock_aiclk, positive=True) and clock_aiclk != report.get("aiclk_mhz"):
        mismatches.append(_mismatch(invariant, ("clock.aiclk_mhz", "power_trace.aiclk_mhz"), "clock.aiclk_mhz does not equal in-run power-trace AICLK"))
    if timing is _MISSING:
        return mismatches
    if not isinstance(timing, bool):
        mismatches.append(_mismatch(invariant, ("timing_evidence",), "timing_evidence must be a boolean"))
        return mismatches
    reason = record.get("timing_evidence_reason")
    provenance = record.get("power_clock_provenance")
    if isinstance(provenance, Mapping):
        if "timing_evidence" in provenance and provenance.get("timing_evidence") != timing:
            mismatches.append(_mismatch(invariant, ("timing_evidence", "power_clock_provenance.timing_evidence"), "power provenance timing_evidence does not match record"))
        if "timing_evidence_reason" in provenance and isinstance(reason, str) and provenance.get("timing_evidence_reason") != reason:
            mismatches.append(_mismatch(invariant, ("timing_evidence_reason", "power_clock_provenance.timing_evidence_reason"), "power provenance timing_evidence_reason does not match record"))
    if timing:
        block = _timing_block_reason(record, ctx, report)
        if block is not None:
            mismatches.append(_mismatch(invariant, ("timing_evidence", "timing_evidence_reason"), f"timing_evidence=true is not permitted: {block}"))
        if (
            declared.get("aiclk_source") != "run_trace_samples"
            and declared.get("aiclk_source") != "legacy_unverified"
        ):
            # Keep the compatibility branch truthful while retaining old
            # board-free callers that explicitly carry legacy_unverified.
            mismatches.append(_mismatch(invariant, ("clock.aiclk_source", "power_clock_provenance.aiclk_source"), "timing AICLK is not sourced from valid in-run trace samples"))
    else:
        if mode in {"default", "explicit"} and (not isinstance(reason, str) or not reason.strip()):
            mismatches.append(_mismatch(invariant, ("timing_evidence", "timing_evidence_reason"), "sampled records with timing_evidence=false require a non-timing reason"))
        if mode == "off" and not isinstance(reason, str):
            absent_reason = record.get("power_trace_absent_reason")
            if absent_reason != "sampler_off_by_design":
                mismatches.append(_mismatch(invariant, ("timing_evidence_reason", "power_trace_absent_reason"), "sampler-off timing evidence requires sampler_off_by_design"))
        if isinstance(reason, str) and reason in {"power_trace_run_samples", "timing"} and mode != "off":
            mismatches.append(_mismatch(invariant, ("timing_evidence_reason",), "timing_evidence=false requires a non-timing reason"))
    return mismatches


def _check_trace_metadata_duplicates(record: Mapping[str, Any], ctx: ValidationContext) -> list[dict[str, Any]]:
    # Keep this as a catalog entry so the nested/top-level relationship is not
    # hidden inside the timing policy.  The physical fact checks are separate.
    del ctx
    invariant = "power_trace.metadata_duplicates"
    declared = _declared_power_metadata(record)
    nested = declared.get("nested", {})
    top = declared.get("top", {})
    mismatches: list[dict[str, Any]] = []
    for nested_name, top_name in {
        "file": "power_trace",
        "sample_count": "power_trace_sample_count",
        "csv_row_count": "power_trace_csv_row_count",
        "valid_row_count": "power_trace_valid_row_count",
        "in_run_valid_row_count": "power_trace_in_run_valid_row_count",
        "sha256": "power_trace_sha256",
    }.items():
        left = nested.get(nested_name, _MISSING)
        right = top.get(nested_name, _MISSING)
        if left is not _MISSING and right is not _MISSING and left is not None and right is not None and left != right:
            label = "SHA-256" if nested_name == "sha256" else nested_name
            mismatches.append(_mismatch(invariant, (f"power_clock_provenance.{nested_name}", top_name), f"power provenance {label} does not match {top_name}"))
    return mismatches


RESIDENT_INVARIANT_CATALOG: tuple[ResidentInvariant, ...] = (
    ResidentInvariant(
        "parameters.counts",
        ("parameters.frame_count", "parameters.attempted_frame_count", "parameters.produced_frame_count", "parameters.dropped_frame_count", "parameters.aborted_attempts"),
        "configured, attempted, produced, dropped, and aborted counter relations",
        _check_parameter_counts,
    ),
    ResidentInvariant(
        "raw_timestamps",
        ("raw_timestamps.count", "raw_timestamps.sha256", "timestamps"),
        "raw count/hash and supplied timestamp sequence",
        _check_raw_timestamps,
    ),
    ResidentInvariant(
        "histogram",
        ("histogram.N", "histogram.histogram.bins", "timestamps"),
        "interval N+1, bin total, bounds, bins, and percentile relationships",
        _check_histogram,
    ),
    ResidentInvariant(
        "outlier_analysis",
        ("outlier_analysis.pair_count", "outlier_analysis.frame_start_indices", "outlier_analysis.pairs", "outlier_analysis.pair_sums"),
        "pair objects, sums, endpoints, event arrays, gaps, and raw correspondence",
        _check_pairs,
    ),
    ResidentInvariant(
        "ring.counts",
        ("ring.attempted_frame_count", "ring.produced_frame_count", "ring.consumed_frame_count", "ring.dropped_frame_count", "parameters.ring_pages"),
        "ring counter equality and occupancy",
        _check_ring,
    ),
    ResidentInvariant(
        "sampler.trace_contract",
        ("telemetry_sampler.mode", "telemetry_sampler.interval_seconds", "power_trace", "power_trace_absent_reason"),
        "sampler mode, interval contract, and trace presence/absence",
        _check_sampler_contract,
    ),
    ResidentInvariant(
        "power_trace.facts",
        ("power_trace", "power_clock_provenance", "power_trace_sha256"),
        "trace bytes, rows, timestamps, run bounds, AICLK, and PR #109 coverage",
        _check_power_trace_facts,
    ),
    ResidentInvariant(
        "power_trace.metadata_duplicates",
        ("power_clock_provenance", "power_trace_sample_count", "power_trace_sha256"),
        "nested and top-level trace metadata equality",
        _check_trace_metadata_duplicates,
    ),
    ResidentInvariant(
        "clock.timing_evidence",
        ("clock.aiclk_mhz", "clock.aiclk_source", "timing_evidence", "timing_evidence_reason"),
        "in-run AICLK provenance and non-timing evidence policy",
        _check_clock_and_timing,
    ),
)


def _apply_builder_timing_policy(
    record: dict[str, Any], ctx: ValidationContext, report: Mapping[str, Any] | None
) -> None:
    """Force unsafe builder claims false without weakening numeric checks."""
    reason = _timing_block_reason(record, ctx, report)
    timing = record.get("timing_evidence")
    if reason is not None and timing is True:
        record["timing_evidence"] = False
        record["timing_evidence_reason"] = reason
        provenance = record.get("power_clock_provenance")
        if isinstance(provenance, dict):
            provenance["timing_evidence"] = False
            provenance["timing_evidence_reason"] = reason
    elif timing is False:
        current_reason = record.get("timing_evidence_reason")
        if not isinstance(current_reason, str) or not current_reason.strip():
            record["timing_evidence_reason"] = reason or "timing_evidence_false"
            provenance = record.get("power_clock_provenance")
            if isinstance(provenance, dict):
                provenance["timing_evidence_reason"] = record["timing_evidence_reason"]


def validate_resident_record(
    record: Mapping[str, Any],
    *,
    raw_metadata: Mapping[str, Any] | None = None,
    timestamps: Iterable[int] | None = None,
    power_trace_path: Path | None = None,
    power_trace_metadata: Mapping[str, Any] | None = None,
    power_trace_bytes: bytes | None = None,
    raw_bytes: bytes | None = None,
    builder: bool = False,
    strict_trace: bool = True,
    raise_on_error: bool | None = None,
) -> dict[str, Any]:
    """Validate one record through the executable shared invariant catalog.

    Analyzer callers use the default report mode.  Builder callers pass
    ``builder=True`` and may use ``raise_on_error=True`` for hard numeric or
    schema contradictions; unsafe timing claims are changed to false with an
    explicit reason before the report is produced.
    """
    if raise_on_error is None:
        raise_on_error = builder
    if not isinstance(record, Mapping):
        report = {
            "valid": False,
            "mismatches": [_mismatch("record", ("record",), "record must be an object")],
            "failures": ["record must be an object"],
            "checks": {},
            "catalog": [entry.name for entry in RESIDENT_INVARIANT_CATALOG],
            "power_trace": None,
        }
        if raise_on_error:
            raise ValueError("record must be an object")
        return report
    timestamp_values = list(timestamps) if timestamps is not None else None
    if raw_metadata is None and raw_bytes is not None:
        raw_metadata = {
            "count": len(raw_bytes) // 8 if len(raw_bytes) % 8 == 0 else -1,
            "sha256": hashlib.sha256(raw_bytes).hexdigest(),
        }
    ctx = ValidationContext(
        timestamps=timestamp_values,
        raw_metadata=raw_metadata,
        power_trace_path=Path(power_trace_path) if power_trace_path is not None else None,
        power_trace_metadata=power_trace_metadata,
        power_trace_bytes=power_trace_bytes,
        strict_trace=strict_trace,
        builder=builder,
    )
    trace_report = _trace_report(record, ctx)
    if builder and isinstance(record, dict):
        _apply_builder_timing_policy(record, ctx, trace_report)
    mismatches: list[dict[str, Any]] = []
    checks: dict[str, Any] = {}
    for entry in RESIDENT_INVARIANT_CATALOG:
        try:
            entry_mismatches = entry.check(record, ctx)
        except (TypeError, ValueError, KeyError, IndexError) as exc:
            entry_mismatches = [_mismatch(entry.name, entry.fields, f"malformed input: {exc}")]
        checks[entry.name] = {
            "ok": not entry_mismatches,
            "fields": list(entry.fields),
            "description": entry.description,
            "mismatches": entry_mismatches,
        }
        mismatches.extend(entry_mismatches)
    failures = [item["message"] for item in mismatches]
    # Preserve the historic check names consumed by board-free callers while
    # keeping their implementation in the catalog entries above.
    if "histogram" in checks:
        checks["histogram_n_plus_one"] = checks["histogram"]
        checks["histogram_bins"] = checks["histogram"]
    if "outlier_analysis" in checks:
        checks["pair_catalog"] = checks["outlier_analysis"]
    if "power_trace.facts" in checks:
        checks["power_trace"] = checks["power_trace.facts"]
    if "clock.timing_evidence" in checks:
        checks["timing_evidence"] = checks["clock.timing_evidence"]
    report: dict[str, Any] = {
        "valid": not mismatches,
        "mismatches": mismatches,
        "failures": failures,
        "checks": checks,
        "catalog": [
            {"name": entry.name, "fields": list(entry.fields), "description": entry.description}
            for entry in RESIDENT_INVARIANT_CATALOG
        ],
        "power_trace": trace_report,
    }
    if raise_on_error and mismatches:
        trace_unusable = (
            builder
            and trace_report is not None
            and (
                trace_report.get("readable") is not True
                or trace_report.get("coverage_complete") is not True
                or trace_report.get("aiclk_source") != "run_trace_samples"
            )
        )
        hard = [
            item
            for item in mismatches
            if not (
                item["invariant"] == "power_trace.facts"
                and (
                    trace_unusable
                    or "unavailable" in item["message"]
                    or "not true" in item["message"]
                    or "not readable" in item["message"]
                    or "coverage_complete" in item["message"]
                    or "valid-row" in item["message"]
                    or "row count" in item["message"]
                    or "columns" in item["message"]
                )
            )
            and item["invariant"] != "clock.timing_evidence"
        ]
        if hard:
            raise ValueError(hard[0]["message"])
    return report


# Descriptive aliases retain the old analyzer import names while pointing to
# the one shared implementation.
validate_record_invariants = validate_resident_record
validate_issue104_record = validate_resident_record
validate_record_power_invariants = validate_resident_record


__all__ = [
    "CLOCK_MODULUS_TICKS",
    "DEFAULT_AICLK_MHZ",
    "DEFAULT_PHASE_WINDOW_MS",
    "LONG_THRESHOLD_TICKS",
    "PAIR_ORDERS",
    "PAIR_TARGET_TICKS",
    "PAIR_TOLERANCE_TICKS",
    "RESIDENT_INVARIANT_CATALOG",
    "SAMPLER_CONTRACT",
    "SHORT_THRESHOLD_TICKS",
    "ResidentInvariant",
    "_count_orders",
    "_detect_pairs",
    "_record_correspondence",
    "build_outlier_analysis",
    "detect_pairs",
    "normalize_sampler_metadata",
    "raw_metadata_matches",
    "record_correspondence",
    "validate_issue104_record",
    "validate_pair_analysis",
    "validate_record_invariants",
    "validate_record_power_invariants",
    "validate_resident_record",
]
