"""Explicit Issue #88 measurement-record field and string allowlist."""

# Runner output vocabularies live here so both the producer and the final
# publication validator consume the same symbols instead of maintaining
# separate, drift-prone spellings.
ISSUE88_STATUS_PASS = "pass"
ISSUE88_STATUS_FAILED = "failed"
ISSUE88_ROW_STATUS_OK = "ok"
ISSUE88_ROW_STATUS_CORRECTNESS_ONLY = "correctness_only"
ISSUE88_ROW_STATUS_PREFLIGHT_REJECTED = "preflight_rejected"
ISSUE88_PREFLIGHT_STATUS_ADMITTED = "admitted"
ISSUE88_PREFLIGHT_STATUS_REJECTED = "rejected_before_allocation"
ISSUE88_TELEMETRY_STATUS_COMPLETE = "complete"
ISSUE88_FIRST_LAUNCH_TIMING = "not run (--first-launch)"
ISSUE88_TIMING_PROTOCOL = "one synchronized warm-up followed by exactly 1,000 synchronized launches"
ISSUE88_STOP_CONDITION_ROW_ERROR = "row_error"
ISSUE88_STOP_CONDITION_TIMEOUT = "row_timeout_s_exceeded"
ISSUE88_STATUS_ROW_VALUES = frozenset(
    {
        ISSUE88_STATUS_PASS,
        ISSUE88_STATUS_FAILED,
        ISSUE88_ROW_STATUS_OK,
        ISSUE88_ROW_STATUS_CORRECTNESS_ONLY,
        ISSUE88_ROW_STATUS_PREFLIGHT_REJECTED,
        ISSUE88_PREFLIGHT_STATUS_ADMITTED,
        ISSUE88_PREFLIGHT_STATUS_REJECTED,
        ISSUE88_TELEMETRY_STATUS_COMPLETE,
        "passed before allocation",
    }
)
ISSUE88_SUCCESSFUL_ROW_STATUSES = frozenset(
    {
        ISSUE88_ROW_STATUS_OK,
        ISSUE88_ROW_STATUS_CORRECTNESS_ONLY,
        ISSUE88_ROW_STATUS_PREFLIGHT_REJECTED,
    }
)
ISSUE88_TIMING_VALUES = frozenset({ISSUE88_FIRST_LAUNCH_TIMING})
ISSUE88_STOP_CONDITIONS = frozenset(
    {ISSUE88_STOP_CONDITION_ROW_ERROR, ISSUE88_STOP_CONDITION_TIMEOUT}
)
ISSUE88_PUBLIC_STRING_VALUES = {
    "status": ISSUE88_STATUS_ROW_VALUES,
    "artifact_status": ISSUE88_STATUS_ROW_VALUES,
    "finite_status": frozenset({ISSUE88_STATUS_PASS, ISSUE88_STATUS_FAILED}),
    "timing": ISSUE88_TIMING_VALUES,
    "stop_condition": ISSUE88_STOP_CONDITIONS,
}
ISSUE88_TRUE_INVERSE_METRIC_REFERENCE = "NumPy complex128 inverse of original FP32 R"
ISSUE88_BF16_MATCHING_METRIC_REFERENCE = (
    "fixed-N=12 Newton-Schulz reference using BF16-rounded R and "
    "X0=I/||original FP32 R||_infinity"
)
ISSUE88_FP32_MATCHING_METRIC_REFERENCE = (
    "fixed-N=12 Newton-Schulz reference using original FP32 R and "
    "X0=I/||original FP32 R||_infinity"
)

ISSUE88_ERROR_CODE_VALUES = {
    "artifact_binding": "artifact_binding_failed",
    "board_selection_failed": "board_selection_failed",
    "board_selection_succeeded": "board_selection_succeeded",
    "correctness_failed": "correctness_failed",
    "device_close_failed": "device_close_failed",
    "device_close_succeeded": "device_close_succeeded",
    "device_open_failed": "device_open_failed",
    "device_test_gate_failed": "device_test_gate_failed",
    "device_session_failed": "device_session_failed",
    "environment_artifact_unreadable": "environment_artifact_unreadable",
    "environment_run_id_missing": "environment_run_id_missing",
    "harness_failed": "harness_failed",
    "harness_succeeded": "harness_succeeded",
    "host_preparation_failed": "host_preparation_failed",
    "image_toolchain_failed": "image_toolchain_failed",
    "image_toolchain_succeeded": "image_toolchain_succeeded",
    "inverse_artifact_persistence_failed": "inverse_artifact_persistence_failed",
    "inverse_outputs_failed": "inverse_outputs_failed",
    "inverse_outputs_succeeded": "inverse_outputs_succeeded",
    "power_sample_invalid": "power_sample_invalid",
    "power_timestamp_invalid": "power_timestamp_invalid",
    "power_trace_failed": "power_trace_failed",
    "power_trace_incomplete": "power_trace_incomplete",
    "power_trace_invalid": "power_trace_invalid",
    "power_trace_no_usable_rows": "power_trace_no_usable_rows",
    "power_trace_succeeded": "power_trace_succeeded",
    "power_trace_timeout": "power_trace_timeout",
    "power_trace_unreadable": "power_trace_unreadable",
    "preflight_rejected": ISSUE88_ROW_STATUS_PREFLIGHT_REJECTED,
    "record_publication_failed": "record_publication_failed",
    "row_cleanup_failed": "row_cleanup_failed",
    "row_execution_failed": "row_execution_failed",
    "row_timeout": "row_timeout",
    "rows_failed": "rows_failed",
    "rows_succeeded": "rows_succeeded",
    "run_id_mismatch": "run_id_mismatch",
}
ISSUE88_ERROR_CODES = frozenset(ISSUE88_ERROR_CODE_VALUES.values())
ISSUE88_STAGE_ERROR_CODES = {
    "close": ISSUE88_ERROR_CODE_VALUES["device_close_failed"],
    "correctness": ISSUE88_ERROR_CODE_VALUES["correctness_failed"],
    "device_test_gate": ISSUE88_ERROR_CODE_VALUES["device_test_gate_failed"],
    "device_session": ISSUE88_ERROR_CODE_VALUES["device_session_failed"],
    "host_preparation": ISSUE88_ERROR_CODE_VALUES["host_preparation_failed"],
    "inverse_artifact_persistence": ISSUE88_ERROR_CODE_VALUES[
        "inverse_artifact_persistence_failed"
    ],
    "open": ISSUE88_ERROR_CODE_VALUES["device_open_failed"],
    "preflight": ISSUE88_ERROR_CODE_VALUES["preflight_rejected"],
    "row": ISSUE88_ERROR_CODE_VALUES["row_execution_failed"],
    "row_cleanup": ISSUE88_ERROR_CODE_VALUES["row_cleanup_failed"],
    "row_timeout": ISSUE88_ERROR_CODE_VALUES["row_timeout"],
    "telemetry.environment": ISSUE88_ERROR_CODE_VALUES[
        "environment_artifact_unreadable"
    ],
    "telemetry.power": (
        ISSUE88_ERROR_CODE_VALUES["power_trace_unreadable"],
        ISSUE88_ERROR_CODE_VALUES["power_trace_invalid"],
    ),
}
ISSUE88_FAILURE_STAGES = frozenset(
    {
        "close",
        "correctness",
        "device_test_gate",
        "device_session",
        "host_preparation",
        "inverse_artifact_persistence",
        "open",
        "preflight",
        "row",
        "row_cleanup",
        "row_timeout",
        "telemetry.environment",
        "telemetry.power",
    }
)
ISSUE88_STATUS_COMPONENT_CODES = {
    "rows": (
        ISSUE88_ERROR_CODE_VALUES["rows_succeeded"],
        ISSUE88_ERROR_CODE_VALUES["rows_failed"],
    ),
    "inverse_outputs": (
        ISSUE88_ERROR_CODE_VALUES["inverse_outputs_succeeded"],
        ISSUE88_ERROR_CODE_VALUES["inverse_outputs_failed"],
    ),
    "board_selection": (
        ISSUE88_ERROR_CODE_VALUES["board_selection_succeeded"],
        ISSUE88_ERROR_CODE_VALUES["board_selection_failed"],
    ),
    "image_toolchain": (
        ISSUE88_ERROR_CODE_VALUES["image_toolchain_succeeded"],
        ISSUE88_ERROR_CODE_VALUES["image_toolchain_failed"],
    ),
    "harness": (
        ISSUE88_ERROR_CODE_VALUES["harness_succeeded"],
        ISSUE88_ERROR_CODE_VALUES["harness_failed"],
    ),
    "power_trace": (
        ISSUE88_ERROR_CODE_VALUES["power_trace_succeeded"],
        ISSUE88_ERROR_CODE_VALUES["power_trace_failed"],
    ),
    "device_close": (
        ISSUE88_ERROR_CODE_VALUES["device_close_succeeded"],
        ISSUE88_ERROR_CODE_VALUES["device_close_failed"],
    ),
}
ISSUE88_ERROR_OBJECT_FIELDS = frozenset(
    {"error", "failure", "binding_error", "poll_error", "close_error", "cleanup_error"}
)

ISSUE88_RECORD_FIELD_TYPES = {
    '16': frozenset(('object',)),
    '32': frozenset(('object',)),
    'CB_IDENTITY': frozenset(('integer',)),
    'CB_NEG_X_IMAG': frozenset(('integer',)),
    'CB_OUTPUT_IMAG': frozenset(('integer',)),
    'CB_OUTPUT_REAL': frozenset(('integer',)),
    'CB_PRODUCT_IMAG': frozenset(('integer',)),
    'CB_PRODUCT_REAL': frozenset(('integer',)),
    'CB_R_IMAG': frozenset(('integer',)),
    'CB_R_NEG_IMAG': frozenset(('integer',)),
    'CB_R_NEG_REAL': frozenset(('integer',)),
    'CB_STATE_IMAG': frozenset(('integer',)),
    'CB_STATE_REAL': frozenset(('integer',)),
    'CB_S_IMAG': frozenset(('integer',)),
    'CB_S_REAL': frozenset(('integer',)),
    'CB_X0_IMAG': frozenset(('integer',)),
    'CB_X0_REAL': frozenset(('integer',)),
    'CB_ZERO': frozenset(('integer',)),
    'L': frozenset(('integer',)),
    'L16_R_L1': frozenset(('object',)),
    'L32_R_DRAM': frozenset(('object',)),
    'R': frozenset(('integer', 'object', 'string')),
    'R_placement': frozenset(('string',)),
    'X0': frozenset(('integer', 'object', 'string')),
    'abnormal_exit': frozenset(('boolean',)),
    'accepted': frozenset(('boolean',)),
    'achieved_tflops': frozenset(('number',)),
    'adr': frozenset(('string',)),
    'aiclk_mhz': frozenset(('string',)),
    'algorithm': frozenset(('object',)),
    'all_lower_is_better': frozenset(('boolean',)),
    'alignment_undefined': frozenset(('boolean',)),
    'allocation_attempted': frozenset(('boolean',)),
    'amplitude_floor': frozenset(('number',)),
    'application': frozenset(('string',)),
    'array': frozenset(('string',)),
    'artifact_file': frozenset(('string',)),
    'artifact_status': frozenset(('string',)),
    'asic_fmax': frozenset(('string',)),
    'asic_temp_c': frozenset(('string',)),
    'batch': frozenset(('integer',)),
    'beam_metrics': frozenset(('object',)),
    'beam_pattern': frozenset(('object', 'string')),
    'beam_response_metrics': frozenset(('object',)),
    'best_complex_scalar': frozenset(('null', 'object')),
    'best_complex_scalar_phase_aligned_complex_response': frozenset(('string',)),
    'best_complex_scalar_phase_aligned_complex_response_relative_frobenius_error': frozenset(('number',)),
    'best_global_complex_scalar_candidate_from_reference': frozenset(('null', 'object')),
    'bf16': frozenset(('string',)),
    'bf16-r-L16': frozenset(('number', 'object', 'string')),
    'bf16-r-L32': frozenset(('number', 'object', 'string')),
    'bf16-r-L32-r-dram': frozenset(('number', 'object', 'string')),
    'board': frozenset(('object',)),
    'board_id': frozenset(('string',)),
    'board_info': frozenset(('object',)),
    'board_power_limit': frozenset(('string',)),
    'board_selection': frozenset(('object',)),
    'board_serial_identity': frozenset(('object',)),
    'board_type': frozenset(('string',)),
    'breakdown': frozenset(('object',)),
    'budget_bytes': frozenset(('integer',)),
    'bus_id': frozenset(('string',)),
    'bus_peak_limit': frozenset(('integer',)),
    'by_look_direction': frozenset(('array', 'null', 'number')),
    'byte_count': frozenset(('integer',)),
    'bytes': frozenset(('integer',)),
    'candidate_finite_values': frozenset(('integer',)),
    'candidate_floored_values': frozenset(('integer',)),
    'candidate_max_absolute_error': frozenset(('null', 'number')),
    'candidate_undefined_look_peaks': frozenset(('integer',)),
    'candidate_vs_conjugate_reference_relative_error_after_scalar': frozenset(('null', 'number')),
    'candidate_vs_transpose_reference_relative_error_after_scalar': frozenset(('null', 'number')),
    'captured_at': frozenset(('string',)),
    'cb_budget_bytes': frozenset(('integer',)),
    'cb_budget_headroom_bytes': frozenset(('integer',)),
    'cb_budget_overage_bytes': frozenset(('integer',)),
    'cb_bytes': frozenset(('integer',)),
    'cb_bytes_by_name': frozenset(('object',)),
    'cb_entries': frozenset(('array', 'object')),
    'circular_buffers': frozenset(('object',)),
    'cleanup': frozenset(('object',)),
    'close_attempted': frozenset(('boolean',)),
    'close_succeeded': frozenset(('boolean',)),
    'cm_fw': frozenset(('string',)),
    'cm_fw_date': frozenset(('string',)),
    'columns': frozenset(('array', 'null', 'string')),
    'commands': frozenset(('object',)),
    'common_metric_reference': frozenset(('object',)),
    'companion_metadata': frozenset(('string',)),
    'comparison_conclusion_reference_policy': frozenset(('string',)),
    'comparison_results': frozenset(('array', 'object')),
    'comparison_rows': frozenset(('array', 'object')),
    'comparisons': frozenset(('array', 'object')),
    'complete': frozenset(('boolean',)),
    'compute': frozenset(('string',)),
    'condition_number': frozenset(('number',)),
    'configs': frozenset(('object',)),
    'configuration_note': frozenset(('string',)),
    'container_device_id': frozenset(('integer',)),
    'coords': frozenset(('string',)),
    'core_count': frozenset(('integer',)),
    'correctness': frozenset(('object',)),
    'correctness_device_test_gate': frozenset(('object',)),
    'correctness_launch': frozenset(('object',)),
    'correctness_reference': frozenset(('string',)),
    'coverage': frozenset(('null', 'object')),
    'coverage_complete': frozenset(('boolean',)),
    'coverage_definition': frozenset(('null', 'string')),
    'covers_run_end': frozenset(('boolean',)),
    'covers_run_start': frozenset(('boolean',)),
    'csv_row_count': frozenset(('integer',)),
    'db_definition': frozenset(('string',)),
    'db_floor_db': frozenset(('number',)),
    'db_pattern': frozenset(('object', 'string')),
    'defined_ratios': frozenset(('integer',)),
    'definition': frozenset(('string',)),
    'definitions': frozenset(('object',)),
    'description': frozenset(('string',)),
    'destination_format': frozenset(('string',)),
    'device_close': frozenset(('object',)),
    'device_close_succeeded': frozenset(('boolean',)),
    'device_id': frozenset(('integer',)),
    'device_inverse_artifact': frozenset(('object',)),
    'device_inverse_artifacts': frozenset(('array', 'object')),
    'device_node': frozenset(('string',)),
    'device_opened': frozenset(('boolean',)),
    'device_test_gate': frozenset(('object', 'string')),
    'dm_app_fw': frozenset(('string',)),
    'dm_bl_fw': frozenset(('string',)),
    'double_buffer': frozenset(('boolean',)),
    'downloaded': frozenset(('boolean',)),
    'dram_speed': frozenset(('string',)),
    'dram_status': frozenset(('boolean',)),
    'dst_full_sync_en': frozenset(('boolean',)),
    'dtype': frozenset(('string',)),
    'element_count': frozenset(('integer',)),
    'element_spacing': frozenset(('string',)),
    'environment': frozenset(('null', 'object')),
    'errors': frozenset(('array', 'object')),
    'eth_fw': frozenset(('string',)),
    'expected_preflight_rejection': frozenset(('boolean',)),
    'external_artifacts': frozenset(('object',)),
    'external_temporary': frozenset(('boolean',)),
    'failure': frozenset(('object',)),
    'failure_stage': frozenset(('null', 'string')),
    'failures': frozenset(('array', 'object')),
    'fallback': frozenset(('boolean',)),
    'fan_rpm_limit': frozenset(('integer',)),
    'file': frozenset(('string',)),
    'fingerprints': frozenset(('object',)),
    'finite': frozenset(('boolean',)),
    'finite_status': frozenset(('string',)),
    'finite_values': frozenset(('integer',)),
    'firmware': frozenset(('object',)),
    'firmware_bundle': frozenset(('string',)),
    'firmwares': frozenset(('object',)),
    'first_at_or_before_run_start': frozenset(('boolean',)),
    'first_launch_only': frozenset(('boolean',)),
    'first_timestamp': frozenset(('string',)),
    'fixed_reference_sha256': frozenset(('string',)),
    'floor_db': frozenset(('number',)),
    'flops_per_launch': frozenset(('integer',)),
    'format': frozenset(('string',)),
    'fp32-r': frozenset(('string',)),
    'fp32-r-L16': frozenset(('number', 'object', 'string')),
    'fp32-r-L32': frozenset(('object', 'string')),
    'fp32-r-L32-r-dram': frozenset(('number', 'object', 'string')),
    'fp32_dest_acc_en': frozenset(('boolean',)),
    'fp32_r_beam_metric_rows': frozenset(('object',)),
    'fp32_r_l32_default_l1_preflight': frozenset(('object',)),
    'fuse_s': frozenset(('boolean',)),
    'fw_bundle_version': frozenset(('string',)),
    'gddr_fw': frozenset(('string',)),
    'generator': frozenset(('string',)),
    'global_scalar_alignment_undefined': frozenset(('boolean',)),
    'harness': frozenset(('object',)),
    'harness_commit': frozenset(('string',)),
    'harness_dirty': frozenset(('boolean',)),
    'hash_definition': frozenset(('string',)),
    'headroom_bytes': frozenset(('integer',)),
    'host_kernel': frozenset(('string',)),
    'identity': frozenset(('integer', 'object', 'string')),
    'imag': frozenset(('number',)),
    'image': frozenset(('string',)),
    'image_digest': frozenset(('string',)),
    'image_pinned': frozenset(('boolean',)),
    'image_toolchain': frozenset(('object',)),
    'immutable_snapshot': frozenset(('boolean',)),
    'initial_value': frozenset(('string',)),
    'input_fingerprint': frozenset(('object',)),
    'input_generation': frozenset(('null', 'object')),
    'input_memory': frozenset(('string',)),
    'invalid_row_count': frozenset(('integer',)),
    'inverse': frozenset(('object', 'string')),
    'inverse_arrays': frozenset(('array', 'object')),
    'inverse_artifact': frozenset(('object',)),
    'inverse_error': frozenset(('object',)),
    'inverse_outputs': frozenset(('object',)),
    'issue': frozenset(('string',)),
    'iterations': frozenset(('integer',)),
    'kernel': frozenset(('string',)),
    'kernel_driver_version': frozenset(('string',)),
    'kmd_version': frozenset(('string',)),
    'l1_preflight_accounting': frozenset(('object',)),
    'last_at_or_after_run_end': frozenset(('boolean',)),
    'last_timestamp': frozenset(('string',)),
    'launched_work': frozenset(('integer',)),
    'launches': frozenset(('integer',)),
    'launches_measured': frozenset(('integer',)),
    'launches_per_row': frozenset(('integer',)),
    'launches_requested': frozenset(('integer',)),
    'limits': frozenset(('object',)),
    'look_directions_deg': frozenset(('array', 'number')),
    'magnitude': frozenset(('number',)),
    'magnitude_max': frozenset(('number',)),
    'magnitude_median': frozenset(('number',)),
    'magnitude_min': frozenset(('number',)),
    'magnitude_p05': frozenset(('number',)),
    'magnitude_p95': frozenset(('number',)),
    'magnitude_response': frozenset(('string',)),
    'magnitude_response_max_absolute_error': frozenset(('null', 'number')),
    'magnitude_response_relative_frobenius_error': frozenset(('null', 'number', 'string')),
    'math_fidelity': frozenset(('string',)),
    'matrix_block': frozenset(('integer',)),
    'matrix_count': frozenset(('integer',)),
    'matrix_sha256': frozenset(('string',)),
    'max_absolute_error_db': frozenset(('null', 'number')),
    'max_cosine_deficit': frozenset(('null', 'number')),
    'mean_by_look_direction': frozenset(('array', 'null', 'number')),
    'mean_cosine_deficit': frozenset(('null', 'number')),
    'measured_rows': frozenset(('object',)),
    'measurement': frozenset(('object',)),
    'measurement_scope': frozenset(('string',)),
    'metric_definition': frozenset(('string',)),
    'metric_definitions': frozenset(('object',)),
    'metric_reference': frozenset(('string',)),
    'metric_reference_labels': frozenset(('object',)),
    'metric_references': frozenset(('object',)),
    'mv_direction_max_cosine_deficit': frozenset(('object',)),
    'mv_weight_direction': frozenset(('object', 'string')),
    'name': frozenset(('string',)),
    'names': frozenset(('object',)),
    'nonempty': frozenset(('boolean',)),
    'nonfinite_ratios': frozenset(('integer',)),
    'normalized_db_floored_pattern': frozenset(('object', 'string')),
    'normalized_environment': frozenset(('null', 'object')),
    'normalized_magnitude_pattern_relative_frobenius_error': frozenset(('null', 'number', 'string')),
    'not_committed': frozenset(('boolean',)),
    'notes': frozenset(('array', 'string')),
    'npy_file_byte_count': frozenset(('integer',)),
    'npy_file_hash_definition': frozenset(('string',)),
    'npy_file_sha256': frozenset(('string',)),
    'ok': frozenset(('boolean',)),
    'output': frozenset(('integer', 'object', 'string')),
    'output_memory': frozenset(('string',)),
    'over_budget_bytes': frozenset(('integer',)),
    'overage_bytes': frozenset(('integer',)),
    'packing': frozenset(('string',)),
    'padded_tile_count': frozenset(('integer',)),
    'partial_rows_retained': frozenset(('boolean',)),
    'pass': frozenset(('boolean',)),
    'pattern_directions_deg': frozenset(('array', 'number')),
    'pci_bus_id': frozenset(('string',)),
    'pcie_speed': frozenset(('integer',)),
    'pcie_width': frozenset(('string',)),
    'performance': frozenset(('object',)),
    'phase_aligned_complex_response_relative_frobenius_error': frozenset(('null', 'number', 'string')),
    'phase_circular_mean_radians': frozenset(('number',)),
    'phase_circular_resultant_length': frozenset(('number',)),
    'phase_degrees': frozenset(('number',)),
    'phase_radians': frozenset(('number',)),
    'phase_sensitive_complex_response': frozenset(('string',)),
    'phase_sensitive_complex_response_max_absolute_error': frozenset(('null', 'number')),
    'phase_sensitive_complex_response_max_relative_error_by_look_direction': frozenset(('array', 'null', 'number')),
    'phase_sensitive_complex_response_relative_error_by_look_direction': frozenset(('array', 'null', 'number')),
    'phase_sensitive_complex_response_relative_frobenius_error': frozenset(('null', 'number', 'string')),
    'physical_device': frozenset(('string',)),
    'physical_tile_count': frozenset(('integer',)),
    'placement': frozenset(('object', 'string')),
    'poll_complete': frozenset(('boolean',)),
    'power_clock_provenance': frozenset(('object',)),
    'power_snapshot': frozenset(('object',)),
    'power_trace': frozenset(('object', 'string')),
    'power_trace_sha256': frozenset(('string',)),
    'power_w': frozenset(('string',)),
    'preflight': frozenset(('object',)),
    'preflight_bytes': frozenset(('integer',)),
    'preflight_over_budget_bytes': frozenset(('integer',)),
    'preflight_status': frozenset(('string',)),
    'provenance': frozenset(('object',)),
    'python': frozenset(('string',)),
    'quality_metric_reference_policy': frozenset(('string',)),
    'quality_vs_matching_reference': frozenset(('null', 'object')),
    'quality_vs_true_inverse': frozenset(('null', 'object', 'string')),
    'r_format': frozenset(('string',)),
    'r_memory': frozenset(('string',)),
    'ratio_summary': frozenset(('null', 'object')),
    'raw_artifact': frozenset(('object',)),
    'raw_record': frozenset(('object',)),
    'raw_schema': frozenset(('string',)),
    'readable': frozenset(('boolean',)),
    'real': frozenset(('number',)),
    'reason': frozenset(('string',)),
    'reasons': frozenset(('array', 'string')),
    'record_schema': frozenset(('string',)),
    'records': frozenset(('array', 'string')),
    'reference_fingerprint': frozenset(('object',)),
    'reference_finite': frozenset(('boolean',)),
    'reference_finite_values': frozenset(('integer',)),
    'reference_floored_values': frozenset(('integer',)),
    'reference_max_absolute_error': frozenset(('number',)),
    'reference_r_sha256': frozenset(('string',)),
    'reference_undefined_look_peaks': frozenset(('integer',)),
    'relative_error': frozenset(('null', 'number', 'string')),
    'relative_error_max': frozenset(('number',)),
    'reference_available': frozenset(('boolean',)),
    'relative_frobenius_error': frozenset(('number',)),
    'relative_frobenius_error_vs_matching_reference': frozenset(('null', 'number', 'string')),
    'relative_frobenius_error_vs_true_inverse': frozenset(('null', 'number', 'string')),
    'relative_residual_after_best_global_scalar': frozenset(('null', 'number')),
    'reset_performed': frozenset(('boolean',)),
    'response_metric_finite_values': frozenset(('integer',)),
    'response_metric_total_values': frozenset(('integer',)),
    'response_metric_undefined_values': frozenset(('integer',)),
    'results': frozenset(('array', 'object')),
    'rms_absolute_error_db': frozenset(('null', 'number')),
    'row': frozenset(('string',)),
    'row_statuses': frozenset(('object',)),
    'row_timeout_s': frozenset(('number',)),
    'rows': frozenset(('array', 'object', 'string')),
    'rows_completed': frozenset(('integer',)),
    'rows_requested': frozenset(('integer',)),
    'run': frozenset(('object',)),
    'run_end': frozenset(('string',)),
    'run_id': frozenset(('string',)),
    'run_protocol': frozenset(('object',)),
    'run_start': frozenset(('string',)),
    'runner': frozenset(('string',)),
    'same_device_session': frozenset(('boolean',)),
    'same_matrix_for_matching_size_variants': frozenset(('boolean',)),
    'same_python_process': frozenset(('boolean',)),
    'sample_count': frozenset(('integer',)),
    'samples': frozenset(('array', 'integer', 'object')),
    'sampling_source': frozenset(('null', 'string')),
    'schema': frozenset(('string',)),
    'scope': frozenset(('string',)),
    'seconds_per_launch_min': frozenset(('number',)),
    'seconds_per_launch_p50': frozenset(('number',)),
    'seconds_per_launch_p99': frozenset(('number',)),
    'seconds_per_launch_p99_9': frozenset(('number',)),
    'seconds_per_launch_samples': frozenset(('array', 'number')),
    'seed': frozenset(('integer',)),
    'selected_controls': frozenset(('object',)),
    'serial': frozenset(('string',)),
    'sha256': frozenset(('string',)),
    'sha256_definition': frozenset(('null', 'string')),
    'shape': frozenset(('array', 'integer')),
    'shape_name': frozenset(('string',)),
    'size': frozenset(('integer',)),
    'source': frozenset(('string',)),
    'source_file': frozenset(('string',)),
    'source_record': frozenset(('object',)),
    'state_format': frozenset(('string',)),
    'static_prefix_bytes': frozenset(('integer',)),
    'status': frozenset(('string',)),
    'status_components': frozenset(('object',)),
    'stop_condition': frozenset(('string',)),
    'steering_array': frozenset(('object',)),
    'stopped_on_failure': frozenset(('boolean',)),
    'storage': frozenset(('string',)),
    'summary_schema': frozenset(('string',)),
    'supersedes': frozenset(('object',)),
    'synchronized': frozenset(('boolean',)),
    'tdc_limit': frozenset(('string',)),
    'tdp_limit': frozenset(('string',)),
    'telemetry': frozenset(('object',)),
    'tensor_bytes': frozenset(('integer',)),
    'tensor_bytes_by_name': frozenset(('object',)),
    'tensor_items': frozenset(('object',)),
    'tflops_derivation': frozenset(('string',)),
    'tflops_fastest_launch_derived': frozenset(('number',)),
    'tflops_min_derived': frozenset(('number',)),
    'tflops_p50_derived': frozenset(('number',)),
    'tflops_p99_9_derived': frozenset(('number',)),
    'tflops_p99_derived': frozenset(('number',)),
    'therm_trip_l1_limit': frozenset(('string',)),
    'thm_limit': frozenset(('string',)),
    'timeout': frozenset(('boolean',)),
    'timestamp_utc': frozenset(('string',)),
    'timestamps_ordered': frozenset(('boolean',)),
    'timestamps_parse': frozenset(('boolean',)),
    'timing': frozenset(('object', 'string')),
    'timing_protocol': frozenset(('string',)),
    'toolchain_release': frozenset(('string',)),
    'total_bytes': frozenset(('integer',)),
    'total_ratios': frozenset(('integer',)),
    'total_values': frozenset(('integer',)),
    'trace': frozenset(('null', 'string')),
    'trace_byte_count': frozenset(('integer', 'null')),
    'trace_sha256': frozenset(('null', 'string')),
    'true_inverse': frozenset(('string',)),
    'true_inverse_finite': frozenset(('boolean',)),
    'true_inverse_sha256': frozenset(('string',)),
    'tt_env_active_release': frozenset(('string',)),
    'tt_flash_version': frozenset(('string',)),
    'unchanged': frozenset(('boolean',)),
    'undefined_values': frozenset(('integer',)),
    'update': frozenset(('string',)),
    'usable_row_count': frozenset(('integer',)),
    'valid_row_count': frozenset(('integer',)),
    'variant': frozenset(('string',)),
    'vdd_max': frozenset(('string',)),
    'vdd_min': frozenset(('string',)),
    'warmup': frozenset(('object',)),
    'watcher': frozenset(('boolean',)),
    'weight_normalization': frozenset(('object',)),
    'weight_ratio_diagnostics': frozenset(('object',)),
    'wrapper': frozenset(('string',)),
    'x0_memory': frozenset(('string',)),
    'x0_sha256': frozenset(('string',)),
    'zero': frozenset(('integer', 'object', 'string')),
}

ISSUE88_RECORD_FIELD_TYPES.update(
    {
        'code': frozenset(('string',)),
        'exception_type': frozenset(('null', 'string')),
        'stage': frozenset(('string',)),
        'error': frozenset(('object',)),
        'binding_error': frozenset(('object',)),
        'poll_error': frozenset(('object',)),
        'close_error': frozenset(('object',)),
        'cleanup_error': frozenset(('object',)),
        'failure': frozenset(('object',)),
        'component': frozenset(('string',)),
        'secondary_failures': frozenset(('array', 'object')),
        'environment_file': frozenset(('null', 'string')),
        'poll_count': frozenset(('integer',)),
        'source_file': frozenset(('null', 'string')),
        'file': frozenset(('null', 'string')),
        'sha256': frozenset(('null', 'string')),
        'byte_count': frozenset(('integer', 'null')),
        'first_timestamp': frozenset(('null', 'string')),
        'last_timestamp': frozenset(('null', 'string')),
        'run_start': frozenset(('null', 'string')),
        'run_end': frozenset(('null', 'string')),
        'environment': frozenset(('null', 'object')),
        'harness_commit': frozenset(('null', 'string')),
        'input_generation': frozenset(('null', 'object')),
        'power_trace': frozenset(('null', 'object', 'string')),
        'power_trace_sha256': frozenset(('null', 'string')),
        'telemetry': frozenset(('null', 'object')),
        'failure_stage': frozenset(('null', 'string')),
    }
)

ISSUE88_FIXED_PUBLIC_STRINGS = frozenset((
    '#88',
    '0.70',
    '0.90',
    '1 - absolute normalized direction cosine',
    '1 - |w_true^H w_device| / (||w_true||_2 ||w_device||_2), w = R^-1 a / (a^H R^-1 a)',
    '110',
    '1350',
    '150',
    '19.6.0.0',
    '20*log10(max(abs(response)/abs(response_at_look), 10**(floor_db/20))); candidate and reference normalized separately',
    '200',
    '2026-10-08-p150a-newton-schulz-issue88-fp32-r-convergence-rerun.json',
    '2026-10-08-p150a-newton-schulz-issue88-fp32-r-placement-followup.json',
    '2026-10-08-p150a-newton-schulz-issue88-fp32-r.json',
    '300',
    '90',
    '<c8',
    'ADR-0005',
    'BF16',
    'BF16-R',
    'BF16-R placement effect at L=32',
    'BF16-R reference uses BF16-rounded R and X0 computed from original R.',
    'CB_IDENTITY',
    'CB_NEG_X_IMAG',
    'CB_OUTPUT_IMAG',
    'CB_OUTPUT_REAL',
    'CB_PRODUCT_IMAG',
    'CB_PRODUCT_REAL',
    'CB_R_IMAG',
    'CB_R_NEG_IMAG',
    'CB_R_NEG_REAL',
    'CB_STATE_IMAG',
    'CB_STATE_REAL',
    'CB_S_IMAG',
    'CB_S_REAL',
    'CB_X0_IMAG',
    'CB_X0_REAL',
    'CB_ZERO',
    'Coverage is complete when the immutable per-run snapshot has at least one usable finite telemetry row, usable timestamps parse in order, its first usable sample is at or before the recorded run start, and its last usable sample timestamp is at or after the recorded run end; the run interval is covered through its end. Rows with unusable power, AICLK, or temperature values are excluded from these checks.',
    'Coverage is complete when the immutable per-run snapshot is readable and nonempty, timestamps parse in order, its first sample is at or before the recorded run start, and its last sample timestamp is at or after the recorded run end; the run interval is covered through its end.',
    'DRAM',
    'Each conclusion uses one declared metric_reference; metrics with different references are reported in separate conclusions.',
    'Each inverse artifact records the SHA-256 of canonical contiguous C-order array payload bytes and the SHA-256 of the complete .npy file, plus shape, dtype, element/matrix counts, and byte counts.',
    'Each quality metric group and its MV/beam submetrics carry a metric_reference; conclusions must not combine distinct references.',
    'Every measured row below is a downloaded device inverse compared with one common original-R true inverse. The preflight-rejected row has no device result; host-only fixed-N metrics are not presented as device results.',
    'Expected host-only preflight rejection; block 8 R-in-L1 exceeds the L1 budget and no placement fallback is performed.',
    'FP32',
    'FP32-R',
    'FP32-R L=32 keeps block 8 and moves only R to explicit DRAM placement.',
    'FP32-R effect at L=16 with R in L1',
    'FP32-R effect at L=32 with R in DRAM',
    'FP32-R reference uses original FP32 R and the same X0 computed from original R.',
    'Fit alpha = vdot(response_candidate, response_reference) / vdot(response_candidate, response_candidate), then report ||alpha * response_candidate - response_reference||_F / ||response_reference||_F',
    'For each inverse P, compute w = P a / (a^H P a) with the fixed _weight contraction, then compare same-array response arrays w^H a(theta) over batch, look, and pattern directions.',
    'HiFi3',
    'I / ||R||_infinity',
    'I/||R||inf',
    'Issue #88 BF16-R versus FP32-R fixed-N=12 comparison with one correctness launch and 1,000 synchronized launches per row.',
    'L1',
    'No host name or user-specific absolute path is included in this record.',
    "Normalize candidate and reference magnitudes separately by each look's sampled look-direction magnitude; compare 20*log10(max(abs(response)/abs(response_at_look), 10**(floor_db/20)))",
    "Normalize candidate and reference magnitudes separately by each look's sampled look-direction magnitude; compare 20*log10(max(magnitude, 10**(floor_db/20))) using RMS and maximum absolute dB error; floor_db=-120 by default",
    'Normalize each candidate and reference look pattern by its own sampled look-direction magnitude, then report the relative Frobenius error of the valid normalized magnitude arrays',
    'NumPy .npy',
    'NumPy complex128 inverse of original FP32 R',
    'R in DRAM is explicit because the selected block-8 R-in-L1 preflight rejects before allocation.',
    'R in DRAM is explicit to match the L=32 FP32-R placement-control row; no placement fallback is performed.',
    'Raw launch samples, fingerprints, correctness metrics, inverse artifact metadata, and sanitized telemetry are retained.',
    'SHA-256 of the complete .npy file bytes, including header and payload',
    'SHA-256 of the complete immutable per-run power CSV snapshot bytes',
    'SHA-256 of the downloaded inverse converted with np.ascontiguousarray and viewed as uint8 in C order; excludes the .npy header and preserves the downloaded dtype byte order',
    'The FP32-R/L=32/R-in-L1 row allocated and launched zero work because host preflight rejected it before allocation.',
    'The earlier device records did not retain the downloaded device inverse arrays needed to recompute corrected beam diagnostics.',
    'The five measured rows each retained one synchronized inverse array as a basename-only external .npy artifact.',
    'The four beam metrics are device-output diagnostics under the common original-R true-inverse reference; variant-matched fixed-N metrics are not used for conclusions.',
    'The historical beam metrics used the defective batched _weight einsum denominator and are not evidence.',
    ISSUE88_FIRST_LAUNCH_TIMING,
    ISSUE88_TIMING_PROTOCOL,
    ISSUE88_TRUE_INVERSE_METRIC_REFERENCE,
    ISSUE88_BF16_MATCHING_METRIC_REFERENCE,
    ISSUE88_FP32_MATCHING_METRIC_REFERENCE,
    ISSUE88_PREFLIGHT_STATUS_ADMITTED,
    'The power trace is an immutable per-run CSV snapshot; its hash, sample count, and coverage fields refer to that snapshot.',
    'The synchronized correctness-launch inverse for each downloaded row is retained as a basename-only NumPy .npy file in the wrapper output directory; the expected preflight rejection has no inverse artifact.',
    'This device-1 retake supersedes the prior Issue #88 device records; every predecessor remains immutable and visible.',
    'X[k+1] = X[k] @ (2I - R @ X[k])',
    'adr-0005-issue88-fp32-r-device1-retake-summary-v1',
    'adr-0005-issue88-fp32-r-raw-v3',
    'adr-0005-issue88-fp32-r-v3',
    'aiclk_mhz',
    'all downloaded inverses have valid retained artifacts',
    'all selected rows succeeded',
    'asic_temp_c',
    'beam response is wᴴ a(theta); reported response-pattern comparisons are over batch, look, and pattern directions',
    'best-complex-scalar phase-aligned complex response',
    'bf16',
    'bf16-r-L16',
    'bf16-r-L32',
    'bf16-r-L32-r-dram',
    'board selection and firmware are verifiable',
    'board_id_alias',
    'candidate_weight/reference_weight where |reference_weight| > 1e-12 * max(|reference_weight|) per vector',
    'complete',
    'default BF16-R/L1 versus FP32-R/DRAM at L=32',
    'device close returned normally',
    'device-1 only',
    'diagonal_pairs_32x32',
    'digest-pinned image and toolchain metadata are present',
    'dram',
    'enodia.tt.bench.newton_schulz_reference.newton_schulz_reference; fixed N=12',
    'enodia.tt.bench.newton_schulz_reference.random_hpd_batch',
    'enodia/tt/bench/run_in_container.sh',
    'equal-spaced linear array',
    'external raw storage; not tracked',
    'fixed-N=12 Newton-Schulz reference using BF16-rounded R and X0=I/||original FP32 R||_infinity',
    'fixed-N=12 Newton-Schulz reference using original FP32 R and X0=I/||original FP32 R||_infinity',
    'flops_per_launch / seconds_per_launch_statistic / 1e12',
    'fp32-r',
    'fp32-r-L16',
    'fp32-r-L32',
    'fp32-r-L32-r-dram',
    'harness commit is valid and the tree is clean',
    'immutable per-run CSV snapshot captured by run_in_container.sh',
    'l1',
    'magnitude response',
    'native_32x32',
    'newton_schulz_L16_b8192',
    'newton_schulz_L32_b8192',
    'normalized dB/floored pattern',
    'ok',
    'one synchronized warm-up followed by exactly 1,000 synchronized launches',
    'one-half wavelength',
    'p150a',
    'pass',
    'passed before allocation',
    'phase-sensitive complex response',
    'power trace coverage is complete',
    'power_w',
    'preflight_rejected',
    'recorded metric/gate only',
    'recorded metric/gate only; existing device-test assertion is unchanged',
    'row correctness and run status gate; existing device-test assertion is unchanged',
    'row correctness and run status gate; unchanged 1e-2 threshold',
    'rejected_before_allocation',
    'selected block-8 L1 budget rejects before allocation; no fallback',
    'timestamp_utc',
    'tools/newton_schulz_issue88.py',
    'w = P a / (aᴴ P a); measure |wᴴ a - 1|',
    '||X_device - R_original^-1||_F / ||R_original^-1||_F',
    '||X_device - X_reference||_F / ||X_reference||_F',
    '||abs(response_candidate) - abs(response_reference)||_F / ||abs(response_reference)||_F, before per-look peak normalization',
    '||response_candidate - response_reference||_F / ||response_reference||_F; complex phase and response scale are retained',
))
